# This file is part of the SV-Benchmarks collection of verification tasks:
# https://github.com/sosy-lab/sv-benchmarks
#
# SPDX-FileCopyrightText: 2025 The SV-Benchmarks Community
#
# SPDX-License-Identifier: Apache-2.0
#
LEVEL := ../

CC.Arch := 64

COMMON_WARNINGS := \
	-Wno-error=overflow

include $(LEVEL)/Makefile.config
