// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module main.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned short SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned short SORT_3;  // BV with 8 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 8);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (8 - 1);
  typedef unsigned short SORT_11;  // BV with 4 bits
  const SORT_11 mask_SORT_11 = (SORT_11)-1 >> (sizeof(SORT_11) * 8 - 4);
  const SORT_11 msb_SORT_11 = (SORT_11)1 << (4 - 1);
  typedef unsigned short SORT_57;  // BV with 10 bits
  const SORT_57 mask_SORT_57 = (SORT_57)-1 >> (sizeof(SORT_57) * 8 - 10);
  const SORT_57 msb_SORT_57 = (SORT_57)1 << (10 - 1);
  typedef unsigned short SORT_65;  // BV with 7 bits
  const SORT_65 mask_SORT_65 = (SORT_65)-1 >> (sizeof(SORT_65) * 8 - 7);
  const SORT_65 msb_SORT_65 = (SORT_65)1 << (7 - 1);
  // Initializing constants ...
  const SORT_1 var_7 = 0;
  const SORT_11 var_12 = 0;
  const SORT_1 var_33 = 1;
  const SORT_57 var_58 = 0;
  const SORT_65 var_66 = 104;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_1 input_5;
  SORT_1 input_6;
  SORT_1 input_82;
  SORT_1 input_88;
  SORT_1 input_92;
  SORT_1 input_98;
  SORT_1 input_104;
  SORT_1 input_113;
  SORT_1 input_121;
  // Collecting state declarations ...
  SORT_1 state_8;
  SORT_11 state_13;
  SORT_1 state_16;
  SORT_1 state_19;
  SORT_1 state_22;
  SORT_1 state_25;
  SORT_1 state_28;
  SORT_1 state_37;
  SORT_1 state_39;
  SORT_1 state_41;
  SORT_1 state_43;
  SORT_1 state_45;
  SORT_1 state_47;
  SORT_1 state_49;
  SORT_1 state_51;
  SORT_1 state_53;
  SORT_1 state_55;
  SORT_57 state_59;
  // Initializing states ...
  SORT_1 init_9_arg_1 = var_7;
  state_8 = init_9_arg_1;
  SORT_11 init_14_arg_1 = var_12;
  state_13 = init_14_arg_1;
  SORT_1 init_17_arg_1 = var_7;
  state_16 = init_17_arg_1;
  SORT_1 init_20_arg_1 = var_7;
  state_19 = init_20_arg_1;
  SORT_1 init_23_arg_1 = var_7;
  state_22 = init_23_arg_1;
  SORT_1 init_26_arg_1 = var_7;
  state_25 = init_26_arg_1;
  SORT_1 init_29_arg_1 = var_7;
  state_28 = init_29_arg_1;
  SORT_1 init_38_arg_1 = var_7;
  state_37 = init_38_arg_1;
  SORT_1 init_40_arg_1 = var_7;
  state_39 = init_40_arg_1;
  SORT_1 init_42_arg_1 = var_7;
  state_41 = init_42_arg_1;
  SORT_1 init_44_arg_1 = var_7;
  state_43 = init_44_arg_1;
  SORT_1 init_46_arg_1 = var_33;
  state_45 = init_46_arg_1;
  SORT_1 init_48_arg_1 = var_7;
  state_47 = init_48_arg_1;
  SORT_1 init_50_arg_1 = var_7;
  state_49 = init_50_arg_1;
  SORT_1 init_52_arg_1 = var_7;
  state_51 = init_52_arg_1;
  SORT_1 init_54_arg_1 = var_7;
  state_53 = init_54_arg_1;
  SORT_1 init_56_arg_1 = var_7;
  state_55 = init_56_arg_1;
  SORT_57 init_60_arg_1 = var_58;
  state_59 = init_60_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_short();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_short();
    input_4 = input_4 & mask_SORT_3;
    input_5 = __VERIFIER_nondet_short();
    input_5 = input_5 & mask_SORT_1;
    input_6 = __VERIFIER_nondet_short();
    input_6 = input_6 & mask_SORT_1;
    input_82 = __VERIFIER_nondet_short();
    input_82 = input_82 & mask_SORT_1;
    input_88 = __VERIFIER_nondet_short();
    input_88 = input_88 & mask_SORT_1;
    input_92 = __VERIFIER_nondet_short();
    input_92 = input_92 & mask_SORT_1;
    input_98 = __VERIFIER_nondet_short();
    input_98 = input_98 & mask_SORT_1;
    input_104 = __VERIFIER_nondet_short();
    input_104 = input_104 & mask_SORT_1;
    input_113 = __VERIFIER_nondet_short();
    input_113 = input_113 & mask_SORT_1;
    input_121 = __VERIFIER_nondet_short();
    input_121 = input_121 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_11 var_31_arg_0 = state_13;
    SORT_1 var_31 = var_31_arg_0 >> 3;
    var_31 = var_31 & mask_SORT_1;
    SORT_1 var_32_arg_0 = var_31;
    SORT_1 var_32 = ~var_32_arg_0;
    var_32 = var_32 & mask_SORT_1;
    SORT_1 var_34_arg_0 = var_32;
    SORT_1 var_34 = ~var_34_arg_0;
    var_34 = var_34 & mask_SORT_1;
    SORT_1 var_35_arg_0 = var_33;
    SORT_1 var_35_arg_1 = var_34;
    SORT_1 var_35 = var_35_arg_0 & var_35_arg_1;
    var_35 = var_35 & mask_SORT_1;
    SORT_1 bad_36_arg_0 = var_35;
    __VERIFIER_assert(!(bad_36_arg_0));
    // Computing next states ...
    SORT_1 next_62_arg_1 = state_8;
    SORT_11 next_63_arg_1 = state_13;
    SORT_65 var_67_arg_0 = var_66;
    SORT_57 var_67 = var_67_arg_0;
    SORT_57 var_68_arg_0 = state_59;
    SORT_57 var_68_arg_1 = var_67;
    SORT_1 var_68 = var_68_arg_0 > var_68_arg_1;
    SORT_1 var_64_arg_0 = state_45;
    SORT_1 var_64_arg_1 = var_7;
    SORT_1 var_64_arg_2 = var_33;
    SORT_1 var_64 = var_64_arg_0 ? var_64_arg_1 : var_64_arg_2;
    SORT_1 var_69_arg_0 = var_68;
    SORT_1 var_69_arg_1 = var_64;
    SORT_1 var_69_arg_2 = var_33;
    SORT_1 var_69 = var_69_arg_0 ? var_69_arg_1 : var_69_arg_2;
    SORT_1 var_70_arg_0 = state_51;
    SORT_1 var_70_arg_1 = var_69;
    SORT_1 var_70_arg_2 = var_33;
    SORT_1 var_70 = var_70_arg_0 ? var_70_arg_1 : var_70_arg_2;
    SORT_1 next_71_arg_1 = var_70;
    SORT_1 var_74_arg_0 = state_43;
    SORT_1 var_74_arg_1 = var_33;
    SORT_1 var_74_arg_2 = state_55;
    SORT_1 var_74 = var_74_arg_0 ? var_74_arg_1 : var_74_arg_2;
    SORT_1 var_75_arg_0 = var_74;
    SORT_1 var_75 = ~var_75_arg_0;
    var_75 = var_75 & mask_SORT_1;
    SORT_1 var_76_arg_0 = input_5;
    SORT_1 var_76 = ~var_76_arg_0;
    var_76 = var_76 & mask_SORT_1;
    SORT_1 var_77_arg_0 = var_75;
    SORT_1 var_77_arg_1 = var_76;
    SORT_1 var_77 = var_77_arg_0 | var_77_arg_1;
    var_77 = var_77 & mask_SORT_1;
    SORT_1 var_78_arg_0 = var_77;
    SORT_1 var_78_arg_1 = var_33;
    SORT_1 var_78_arg_2 = var_7;
    SORT_1 var_78 = var_78_arg_0 ? var_78_arg_1 : var_78_arg_2;
    SORT_1 var_72_arg_0 = state_55;
    SORT_1 var_72_arg_1 = var_33;
    SORT_1 var_72_arg_2 = var_7;
    SORT_1 var_72 = var_72_arg_0 ? var_72_arg_1 : var_72_arg_2;
    SORT_1 var_73_arg_0 = state_43;
    SORT_1 var_73_arg_1 = var_72;
    SORT_1 var_73_arg_2 = state_19;
    SORT_1 var_73 = var_73_arg_0 ? var_73_arg_1 : var_73_arg_2;
    SORT_1 var_79_arg_0 = state_47;
    SORT_1 var_79_arg_1 = var_78;
    SORT_1 var_79_arg_2 = var_73;
    SORT_1 var_79 = var_79_arg_0 ? var_79_arg_1 : var_79_arg_2;
    SORT_1 next_80_arg_1 = var_79;
    SORT_1 next_81_arg_1 = state_22;
    SORT_1 var_84_arg_0 = state_37;
    SORT_1 var_84 = ~var_84_arg_0;
    var_84 = var_84 & mask_SORT_1;
    SORT_1 var_83_arg_0 = state_37;
    SORT_1 var_83_arg_1 = state_25;
    SORT_1 var_83_arg_2 = input_82;
    SORT_1 var_83 = var_83_arg_0 ? var_83_arg_1 : var_83_arg_2;
    SORT_1 var_85_arg_0 = var_84;
    SORT_1 var_85_arg_1 = var_33;
    SORT_1 var_85_arg_2 = var_83;
    SORT_1 var_85 = var_85_arg_0 ? var_85_arg_1 : var_85_arg_2;
    SORT_1 next_86_arg_1 = var_85;
    SORT_1 next_87_arg_1 = state_28;
    SORT_1 var_89_arg_0 = state_37;
    SORT_1 var_89_arg_1 = var_7;
    SORT_1 var_89_arg_2 = input_88;
    SORT_1 var_89 = var_89_arg_0 ? var_89_arg_1 : var_89_arg_2;
    SORT_1 var_90_arg_0 = var_84;
    SORT_1 var_90_arg_1 = var_33;
    SORT_1 var_90_arg_2 = var_89;
    SORT_1 var_90 = var_90_arg_0 ? var_90_arg_1 : var_90_arg_2;
    SORT_1 next_91_arg_1 = var_90;
    SORT_1 var_95_arg_0 = state_39;
    SORT_1 var_95 = ~var_95_arg_0;
    var_95 = var_95 & mask_SORT_1;
    SORT_1 var_94_arg_0 = state_49;
    SORT_1 var_94_arg_1 = var_33;
    SORT_1 var_94_arg_2 = var_7;
    SORT_1 var_94 = var_94_arg_0 ? var_94_arg_1 : var_94_arg_2;
    SORT_1 var_93_arg_0 = state_39;
    SORT_1 var_93_arg_1 = var_7;
    SORT_1 var_93_arg_2 = input_92;
    SORT_1 var_93 = var_93_arg_0 ? var_93_arg_1 : var_93_arg_2;
    SORT_1 var_96_arg_0 = var_95;
    SORT_1 var_96_arg_1 = var_94;
    SORT_1 var_96_arg_2 = var_93;
    SORT_1 var_96 = var_96_arg_0 ? var_96_arg_1 : var_96_arg_2;
    SORT_1 next_97_arg_1 = var_96;
    SORT_1 var_101_arg_0 = state_41;
    SORT_1 var_101 = ~var_101_arg_0;
    var_101 = var_101 & mask_SORT_1;
    SORT_1 var_100_arg_0 = state_53;
    SORT_1 var_100_arg_1 = var_33;
    SORT_1 var_100_arg_2 = var_7;
    SORT_1 var_100 = var_100_arg_0 ? var_100_arg_1 : var_100_arg_2;
    SORT_1 var_99_arg_0 = state_41;
    SORT_1 var_99_arg_1 = var_7;
    SORT_1 var_99_arg_2 = input_98;
    SORT_1 var_99 = var_99_arg_0 ? var_99_arg_1 : var_99_arg_2;
    SORT_1 var_102_arg_0 = var_101;
    SORT_1 var_102_arg_1 = var_100;
    SORT_1 var_102_arg_2 = var_99;
    SORT_1 var_102 = var_102_arg_0 ? var_102_arg_1 : var_102_arg_2;
    SORT_1 next_103_arg_1 = var_102;
    SORT_1 var_106_arg_0 = state_53;
    SORT_1 var_106_arg_1 = var_33;
    SORT_1 var_106_arg_2 = state_43;
    SORT_1 var_106 = var_106_arg_0 ? var_106_arg_1 : var_106_arg_2;
    SORT_1 var_105_arg_0 = state_41;
    SORT_1 var_105_arg_1 = var_7;
    SORT_1 var_105_arg_2 = input_104;
    SORT_1 var_105 = var_105_arg_0 ? var_105_arg_1 : var_105_arg_2;
    SORT_1 var_107_arg_0 = var_101;
    SORT_1 var_107_arg_1 = var_106;
    SORT_1 var_107_arg_2 = var_105;
    SORT_1 var_107 = var_107_arg_0 ? var_107_arg_1 : var_107_arg_2;
    SORT_1 next_108_arg_1 = var_107;
    SORT_1 var_109_arg_0 = state_45;
    SORT_1 var_109_arg_1 = var_33;
    SORT_1 var_109_arg_2 = var_7;
    SORT_1 var_109 = var_109_arg_0 ? var_109_arg_1 : var_109_arg_2;
    SORT_1 var_110_arg_0 = var_68;
    SORT_1 var_110_arg_1 = var_109;
    SORT_1 var_110_arg_2 = state_45;
    SORT_1 var_110 = var_110_arg_0 ? var_110_arg_1 : var_110_arg_2;
    SORT_1 var_111_arg_0 = state_51;
    SORT_1 var_111_arg_1 = var_110;
    SORT_1 var_111_arg_2 = state_45;
    SORT_1 var_111 = var_111_arg_0 ? var_111_arg_1 : var_111_arg_2;
    SORT_1 next_112_arg_1 = var_111;
    SORT_1 var_114_arg_0 = state_41;
    SORT_1 var_114_arg_1 = var_33;
    SORT_1 var_114_arg_2 = input_113;
    SORT_1 var_114 = var_114_arg_0 ? var_114_arg_1 : var_114_arg_2;
    SORT_1 var_115_arg_0 = var_101;
    SORT_1 var_115_arg_1 = state_47;
    SORT_1 var_115_arg_2 = var_114;
    SORT_1 var_115 = var_115_arg_0 ? var_115_arg_1 : var_115_arg_2;
    SORT_1 next_116_arg_1 = var_115;
    SORT_1 next_117_arg_1 = state_49;
    SORT_1 var_118_arg_0 = var_77;
    SORT_1 var_118_arg_1 = state_51;
    SORT_1 var_118_arg_2 = var_33;
    SORT_1 var_118 = var_118_arg_0 ? var_118_arg_1 : var_118_arg_2;
    SORT_1 var_119_arg_0 = state_47;
    SORT_1 var_119_arg_1 = var_118;
    SORT_1 var_119_arg_2 = state_51;
    SORT_1 var_119 = var_119_arg_0 ? var_119_arg_1 : var_119_arg_2;
    SORT_1 next_120_arg_1 = var_119;
    SORT_1 var_122_arg_0 = state_39;
    SORT_1 var_122_arg_1 = var_33;
    SORT_1 var_122_arg_2 = input_121;
    SORT_1 var_122 = var_122_arg_0 ? var_122_arg_1 : var_122_arg_2;
    SORT_1 var_123_arg_0 = var_95;
    SORT_1 var_123_arg_1 = state_53;
    SORT_1 var_123_arg_2 = var_122;
    SORT_1 var_123 = var_123_arg_0 ? var_123_arg_1 : var_123_arg_2;
    SORT_1 next_124_arg_1 = var_123;
    SORT_1 next_125_arg_1 = var_74;
    SORT_1 var_126_arg_0 = var_33;
    SORT_57 var_126 = var_126_arg_0;
    SORT_57 var_127_arg_0 = state_59;
    SORT_57 var_127_arg_1 = var_126;
    SORT_57 var_127 = var_127_arg_0 + var_127_arg_1;
    var_127 = var_127 & mask_SORT_57;
    SORT_1 var_128_arg_0 = var_68;
    SORT_57 var_128_arg_1 = var_58;
    SORT_57 var_128_arg_2 = var_127;
    SORT_57 var_128 = var_128_arg_0 ? var_128_arg_1 : var_128_arg_2;
    SORT_1 var_129_arg_0 = state_51;
    SORT_57 var_129_arg_1 = var_128;
    SORT_57 var_129_arg_2 = state_59;
    SORT_57 var_129 = var_129_arg_0 ? var_129_arg_1 : var_129_arg_2;
    SORT_57 next_130_arg_1 = var_129;
    // Assigning next states ...
    state_8 = next_62_arg_1;
    state_13 = next_63_arg_1;
    state_16 = next_71_arg_1;
    state_19 = next_80_arg_1;
    state_22 = next_81_arg_1;
    state_25 = next_86_arg_1;
    state_28 = next_87_arg_1;
    state_37 = next_91_arg_1;
    state_39 = next_97_arg_1;
    state_41 = next_103_arg_1;
    state_43 = next_108_arg_1;
    state_45 = next_112_arg_1;
    state_47 = next_116_arg_1;
    state_49 = next_117_arg_1;
    state_51 = next_120_arg_1;
    state_53 = next_124_arg_1;
    state_55 = next_125_arg_1;
    state_59 = next_130_arg_1;
  }
}
