// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module main.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned int SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned int SORT_8;  // BV with 32 bits
  const SORT_8 mask_SORT_8 = (SORT_8)-1 >> (sizeof(SORT_8) * 8 - 32);
  const SORT_8 msb_SORT_8 = (SORT_8)1 << (32 - 1);
  typedef unsigned int SORT_12;  // BV with 30 bits
  const SORT_12 mask_SORT_12 = (SORT_12)-1 >> (sizeof(SORT_12) * 8 - 30);
  const SORT_12 msb_SORT_12 = (SORT_12)1 << (30 - 1);
  // Initializing constants ...
  const SORT_1 var_3 = 1;
  const SORT_8 var_9 = 4294967295;
  const SORT_12 var_13 = 1073741823;
  const SORT_1 var_17 = 0;
  // Collecting input declarations ...
  SORT_1 input_2;
  // Collecting state declarations ...
  // Initializing states ...
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_int();
    input_2 = input_2 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_4_arg_0 = var_3;
    SORT_1 var_4 = ~var_4_arg_0;
    var_4 = var_4 & mask_SORT_1;
    SORT_1 var_5_arg_0 = var_3;
    SORT_1 var_5_arg_1 = var_4;
    SORT_1 var_5 = var_5_arg_0 & var_5_arg_1;
    var_5 = var_5 & mask_SORT_1;
    SORT_1 bad_6_arg_0 = var_5;
    __VERIFIER_assert(!(bad_6_arg_0));
    // Computing next states ...
    // Assigning next states ...
  }
}
