// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module main.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned short SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned short SORT_3;  // BV with 8 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 8);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (8 - 1);
  typedef unsigned short SORT_11;  // BV with 4 bits
  const SORT_11 mask_SORT_11 = (SORT_11)-1 >> (sizeof(SORT_11) * 8 - 4);
  const SORT_11 msb_SORT_11 = (SORT_11)1 << (4 - 1);
  typedef unsigned short SORT_55;  // BV with 10 bits
  const SORT_55 mask_SORT_55 = (SORT_55)-1 >> (sizeof(SORT_55) * 8 - 10);
  const SORT_55 msb_SORT_55 = (SORT_55)1 << (10 - 1);
  typedef unsigned short SORT_63;  // BV with 7 bits
  const SORT_63 mask_SORT_63 = (SORT_63)-1 >> (sizeof(SORT_63) * 8 - 7);
  const SORT_63 msb_SORT_63 = (SORT_63)1 << (7 - 1);
  // Initializing constants ...
  const SORT_1 var_7 = 0;
  const SORT_11 var_12 = 0;
  const SORT_1 var_31 = 1;
  const SORT_55 var_56 = 0;
  const SORT_63 var_64 = 104;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_1 input_5;
  SORT_1 input_6;
  SORT_1 input_80;
  SORT_1 input_86;
  SORT_1 input_90;
  SORT_1 input_96;
  SORT_1 input_102;
  SORT_1 input_111;
  SORT_1 input_119;
  // Collecting state declarations ...
  SORT_1 state_8;
  SORT_11 state_13;
  SORT_1 state_16;
  SORT_1 state_19;
  SORT_1 state_22;
  SORT_1 state_25;
  SORT_1 state_28;
  SORT_1 state_35;
  SORT_1 state_37;
  SORT_1 state_39;
  SORT_1 state_41;
  SORT_1 state_43;
  SORT_1 state_45;
  SORT_1 state_47;
  SORT_1 state_49;
  SORT_1 state_51;
  SORT_1 state_53;
  SORT_55 state_57;
  // Initializing states ...
  SORT_1 init_9_arg_1 = var_7;
  state_8 = init_9_arg_1;
  SORT_11 init_14_arg_1 = var_12;
  state_13 = init_14_arg_1;
  SORT_1 init_17_arg_1 = var_7;
  state_16 = init_17_arg_1;
  SORT_1 init_20_arg_1 = var_7;
  state_19 = init_20_arg_1;
  SORT_1 init_23_arg_1 = var_7;
  state_22 = init_23_arg_1;
  SORT_1 init_26_arg_1 = var_7;
  state_25 = init_26_arg_1;
  SORT_1 init_29_arg_1 = var_7;
  state_28 = init_29_arg_1;
  SORT_1 init_36_arg_1 = var_7;
  state_35 = init_36_arg_1;
  SORT_1 init_38_arg_1 = var_7;
  state_37 = init_38_arg_1;
  SORT_1 init_40_arg_1 = var_7;
  state_39 = init_40_arg_1;
  SORT_1 init_42_arg_1 = var_7;
  state_41 = init_42_arg_1;
  SORT_1 init_44_arg_1 = var_31;
  state_43 = init_44_arg_1;
  SORT_1 init_46_arg_1 = var_7;
  state_45 = init_46_arg_1;
  SORT_1 init_48_arg_1 = var_7;
  state_47 = init_48_arg_1;
  SORT_1 init_50_arg_1 = var_7;
  state_49 = init_50_arg_1;
  SORT_1 init_52_arg_1 = var_7;
  state_51 = init_52_arg_1;
  SORT_1 init_54_arg_1 = var_7;
  state_53 = init_54_arg_1;
  SORT_55 init_58_arg_1 = var_56;
  state_57 = init_58_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_short();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_short();
    input_4 = input_4 & mask_SORT_3;
    input_5 = __VERIFIER_nondet_short();
    input_5 = input_5 & mask_SORT_1;
    input_6 = __VERIFIER_nondet_short();
    input_6 = input_6 & mask_SORT_1;
    input_80 = __VERIFIER_nondet_short();
    input_80 = input_80 & mask_SORT_1;
    input_86 = __VERIFIER_nondet_short();
    input_86 = input_86 & mask_SORT_1;
    input_90 = __VERIFIER_nondet_short();
    input_90 = input_90 & mask_SORT_1;
    input_96 = __VERIFIER_nondet_short();
    input_96 = input_96 & mask_SORT_1;
    input_102 = __VERIFIER_nondet_short();
    input_102 = input_102 & mask_SORT_1;
    input_111 = __VERIFIER_nondet_short();
    input_111 = input_111 & mask_SORT_1;
    input_119 = __VERIFIER_nondet_short();
    input_119 = input_119 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_32_arg_0 = var_31;
    SORT_1 var_32 = ~var_32_arg_0;
    var_32 = var_32 & mask_SORT_1;
    SORT_1 var_33_arg_0 = var_31;
    SORT_1 var_33_arg_1 = var_32;
    SORT_1 var_33 = var_33_arg_0 & var_33_arg_1;
    var_33 = var_33 & mask_SORT_1;
    SORT_1 bad_34_arg_0 = var_33;
    __VERIFIER_assert(!(bad_34_arg_0));
    // Computing next states ...
    SORT_1 next_60_arg_1 = state_8;
    SORT_11 next_61_arg_1 = state_13;
    SORT_63 var_65_arg_0 = var_64;
    SORT_55 var_65 = var_65_arg_0;
    SORT_55 var_66_arg_0 = state_57;
    SORT_55 var_66_arg_1 = var_65;
    SORT_1 var_66 = var_66_arg_0 > var_66_arg_1;
    SORT_1 var_62_arg_0 = state_43;
    SORT_1 var_62_arg_1 = var_7;
    SORT_1 var_62_arg_2 = var_31;
    SORT_1 var_62 = var_62_arg_0 ? var_62_arg_1 : var_62_arg_2;
    SORT_1 var_67_arg_0 = var_66;
    SORT_1 var_67_arg_1 = var_62;
    SORT_1 var_67_arg_2 = var_31;
    SORT_1 var_67 = var_67_arg_0 ? var_67_arg_1 : var_67_arg_2;
    SORT_1 var_68_arg_0 = state_49;
    SORT_1 var_68_arg_1 = var_67;
    SORT_1 var_68_arg_2 = var_31;
    SORT_1 var_68 = var_68_arg_0 ? var_68_arg_1 : var_68_arg_2;
    SORT_1 next_69_arg_1 = var_68;
    SORT_1 var_72_arg_0 = state_41;
    SORT_1 var_72_arg_1 = var_31;
    SORT_1 var_72_arg_2 = state_53;
    SORT_1 var_72 = var_72_arg_0 ? var_72_arg_1 : var_72_arg_2;
    SORT_1 var_73_arg_0 = var_72;
    SORT_1 var_73 = ~var_73_arg_0;
    var_73 = var_73 & mask_SORT_1;
    SORT_1 var_74_arg_0 = input_5;
    SORT_1 var_74 = ~var_74_arg_0;
    var_74 = var_74 & mask_SORT_1;
    SORT_1 var_75_arg_0 = var_73;
    SORT_1 var_75_arg_1 = var_74;
    SORT_1 var_75 = var_75_arg_0 | var_75_arg_1;
    var_75 = var_75 & mask_SORT_1;
    SORT_1 var_76_arg_0 = var_75;
    SORT_1 var_76_arg_1 = var_31;
    SORT_1 var_76_arg_2 = var_7;
    SORT_1 var_76 = var_76_arg_0 ? var_76_arg_1 : var_76_arg_2;
    SORT_1 var_70_arg_0 = state_53;
    SORT_1 var_70_arg_1 = var_31;
    SORT_1 var_70_arg_2 = var_7;
    SORT_1 var_70 = var_70_arg_0 ? var_70_arg_1 : var_70_arg_2;
    SORT_1 var_71_arg_0 = state_41;
    SORT_1 var_71_arg_1 = var_70;
    SORT_1 var_71_arg_2 = state_19;
    SORT_1 var_71 = var_71_arg_0 ? var_71_arg_1 : var_71_arg_2;
    SORT_1 var_77_arg_0 = state_45;
    SORT_1 var_77_arg_1 = var_76;
    SORT_1 var_77_arg_2 = var_71;
    SORT_1 var_77 = var_77_arg_0 ? var_77_arg_1 : var_77_arg_2;
    SORT_1 next_78_arg_1 = var_77;
    SORT_1 next_79_arg_1 = state_22;
    SORT_1 var_82_arg_0 = state_35;
    SORT_1 var_82 = ~var_82_arg_0;
    var_82 = var_82 & mask_SORT_1;
    SORT_1 var_81_arg_0 = state_35;
    SORT_1 var_81_arg_1 = state_25;
    SORT_1 var_81_arg_2 = input_80;
    SORT_1 var_81 = var_81_arg_0 ? var_81_arg_1 : var_81_arg_2;
    SORT_1 var_83_arg_0 = var_82;
    SORT_1 var_83_arg_1 = var_31;
    SORT_1 var_83_arg_2 = var_81;
    SORT_1 var_83 = var_83_arg_0 ? var_83_arg_1 : var_83_arg_2;
    SORT_1 next_84_arg_1 = var_83;
    SORT_1 next_85_arg_1 = state_28;
    SORT_1 var_87_arg_0 = state_35;
    SORT_1 var_87_arg_1 = var_7;
    SORT_1 var_87_arg_2 = input_86;
    SORT_1 var_87 = var_87_arg_0 ? var_87_arg_1 : var_87_arg_2;
    SORT_1 var_88_arg_0 = var_82;
    SORT_1 var_88_arg_1 = var_31;
    SORT_1 var_88_arg_2 = var_87;
    SORT_1 var_88 = var_88_arg_0 ? var_88_arg_1 : var_88_arg_2;
    SORT_1 next_89_arg_1 = var_88;
    SORT_1 var_93_arg_0 = state_37;
    SORT_1 var_93 = ~var_93_arg_0;
    var_93 = var_93 & mask_SORT_1;
    SORT_1 var_92_arg_0 = state_47;
    SORT_1 var_92_arg_1 = var_31;
    SORT_1 var_92_arg_2 = var_7;
    SORT_1 var_92 = var_92_arg_0 ? var_92_arg_1 : var_92_arg_2;
    SORT_1 var_91_arg_0 = state_37;
    SORT_1 var_91_arg_1 = var_7;
    SORT_1 var_91_arg_2 = input_90;
    SORT_1 var_91 = var_91_arg_0 ? var_91_arg_1 : var_91_arg_2;
    SORT_1 var_94_arg_0 = var_93;
    SORT_1 var_94_arg_1 = var_92;
    SORT_1 var_94_arg_2 = var_91;
    SORT_1 var_94 = var_94_arg_0 ? var_94_arg_1 : var_94_arg_2;
    SORT_1 next_95_arg_1 = var_94;
    SORT_1 var_99_arg_0 = state_39;
    SORT_1 var_99 = ~var_99_arg_0;
    var_99 = var_99 & mask_SORT_1;
    SORT_1 var_98_arg_0 = state_51;
    SORT_1 var_98_arg_1 = var_31;
    SORT_1 var_98_arg_2 = var_7;
    SORT_1 var_98 = var_98_arg_0 ? var_98_arg_1 : var_98_arg_2;
    SORT_1 var_97_arg_0 = state_39;
    SORT_1 var_97_arg_1 = var_7;
    SORT_1 var_97_arg_2 = input_96;
    SORT_1 var_97 = var_97_arg_0 ? var_97_arg_1 : var_97_arg_2;
    SORT_1 var_100_arg_0 = var_99;
    SORT_1 var_100_arg_1 = var_98;
    SORT_1 var_100_arg_2 = var_97;
    SORT_1 var_100 = var_100_arg_0 ? var_100_arg_1 : var_100_arg_2;
    SORT_1 next_101_arg_1 = var_100;
    SORT_1 var_104_arg_0 = state_51;
    SORT_1 var_104_arg_1 = var_31;
    SORT_1 var_104_arg_2 = state_41;
    SORT_1 var_104 = var_104_arg_0 ? var_104_arg_1 : var_104_arg_2;
    SORT_1 var_103_arg_0 = state_39;
    SORT_1 var_103_arg_1 = var_7;
    SORT_1 var_103_arg_2 = input_102;
    SORT_1 var_103 = var_103_arg_0 ? var_103_arg_1 : var_103_arg_2;
    SORT_1 var_105_arg_0 = var_99;
    SORT_1 var_105_arg_1 = var_104;
    SORT_1 var_105_arg_2 = var_103;
    SORT_1 var_105 = var_105_arg_0 ? var_105_arg_1 : var_105_arg_2;
    SORT_1 next_106_arg_1 = var_105;
    SORT_1 var_107_arg_0 = state_43;
    SORT_1 var_107_arg_1 = var_31;
    SORT_1 var_107_arg_2 = var_7;
    SORT_1 var_107 = var_107_arg_0 ? var_107_arg_1 : var_107_arg_2;
    SORT_1 var_108_arg_0 = var_66;
    SORT_1 var_108_arg_1 = var_107;
    SORT_1 var_108_arg_2 = state_43;
    SORT_1 var_108 = var_108_arg_0 ? var_108_arg_1 : var_108_arg_2;
    SORT_1 var_109_arg_0 = state_49;
    SORT_1 var_109_arg_1 = var_108;
    SORT_1 var_109_arg_2 = state_43;
    SORT_1 var_109 = var_109_arg_0 ? var_109_arg_1 : var_109_arg_2;
    SORT_1 next_110_arg_1 = var_109;
    SORT_1 var_112_arg_0 = state_39;
    SORT_1 var_112_arg_1 = var_31;
    SORT_1 var_112_arg_2 = input_111;
    SORT_1 var_112 = var_112_arg_0 ? var_112_arg_1 : var_112_arg_2;
    SORT_1 var_113_arg_0 = var_99;
    SORT_1 var_113_arg_1 = state_45;
    SORT_1 var_113_arg_2 = var_112;
    SORT_1 var_113 = var_113_arg_0 ? var_113_arg_1 : var_113_arg_2;
    SORT_1 next_114_arg_1 = var_113;
    SORT_1 next_115_arg_1 = state_47;
    SORT_1 var_116_arg_0 = var_75;
    SORT_1 var_116_arg_1 = state_49;
    SORT_1 var_116_arg_2 = var_31;
    SORT_1 var_116 = var_116_arg_0 ? var_116_arg_1 : var_116_arg_2;
    SORT_1 var_117_arg_0 = state_45;
    SORT_1 var_117_arg_1 = var_116;
    SORT_1 var_117_arg_2 = state_49;
    SORT_1 var_117 = var_117_arg_0 ? var_117_arg_1 : var_117_arg_2;
    SORT_1 next_118_arg_1 = var_117;
    SORT_1 var_120_arg_0 = state_37;
    SORT_1 var_120_arg_1 = var_31;
    SORT_1 var_120_arg_2 = input_119;
    SORT_1 var_120 = var_120_arg_0 ? var_120_arg_1 : var_120_arg_2;
    SORT_1 var_121_arg_0 = var_93;
    SORT_1 var_121_arg_1 = state_51;
    SORT_1 var_121_arg_2 = var_120;
    SORT_1 var_121 = var_121_arg_0 ? var_121_arg_1 : var_121_arg_2;
    SORT_1 next_122_arg_1 = var_121;
    SORT_1 next_123_arg_1 = var_72;
    SORT_1 var_124_arg_0 = var_31;
    SORT_55 var_124 = var_124_arg_0;
    SORT_55 var_125_arg_0 = state_57;
    SORT_55 var_125_arg_1 = var_124;
    SORT_55 var_125 = var_125_arg_0 + var_125_arg_1;
    var_125 = var_125 & mask_SORT_55;
    SORT_1 var_126_arg_0 = var_66;
    SORT_55 var_126_arg_1 = var_56;
    SORT_55 var_126_arg_2 = var_125;
    SORT_55 var_126 = var_126_arg_0 ? var_126_arg_1 : var_126_arg_2;
    SORT_1 var_127_arg_0 = state_49;
    SORT_55 var_127_arg_1 = var_126;
    SORT_55 var_127_arg_2 = state_57;
    SORT_55 var_127 = var_127_arg_0 ? var_127_arg_1 : var_127_arg_2;
    SORT_55 next_128_arg_1 = var_127;
    // Assigning next states ...
    state_8 = next_60_arg_1;
    state_13 = next_61_arg_1;
    state_16 = next_69_arg_1;
    state_19 = next_78_arg_1;
    state_22 = next_79_arg_1;
    state_25 = next_84_arg_1;
    state_28 = next_85_arg_1;
    state_35 = next_89_arg_1;
    state_37 = next_95_arg_1;
    state_39 = next_101_arg_1;
    state_41 = next_106_arg_1;
    state_43 = next_110_arg_1;
    state_45 = next_114_arg_1;
    state_47 = next_115_arg_1;
    state_49 = next_118_arg_1;
    state_51 = next_122_arg_1;
    state_53 = next_123_arg_1;
    state_57 = next_128_arg_1;
  }
}
