// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module IPBDP_hier.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned int SORT_1;  // BV with 16 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 16);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (16 - 1);
  typedef unsigned int SORT_14;  // BV with 1 bits
  const SORT_14 mask_SORT_14 = (SORT_14)-1 >> (sizeof(SORT_14) * 8 - 1);
  const SORT_14 msb_SORT_14 = (SORT_14)1 << (1 - 1);
  typedef unsigned int SORT_20;  // BV with 2 bits
  const SORT_20 mask_SORT_20 = (SORT_20)-1 >> (sizeof(SORT_20) * 8 - 2);
  const SORT_20 msb_SORT_20 = (SORT_20)1 << (2 - 1);
  typedef unsigned int SORT_22;  // BV with 8 bits
  const SORT_22 mask_SORT_22 = (SORT_22)-1 >> (sizeof(SORT_22) * 8 - 8);
  const SORT_22 msb_SORT_22 = (SORT_22)1 << (8 - 1);
  typedef unsigned int SORT_35;  // BV with 7 bits
  const SORT_35 mask_SORT_35 = (SORT_35)-1 >> (sizeof(SORT_35) * 8 - 7);
  const SORT_35 msb_SORT_35 = (SORT_35)1 << (7 - 1);
  typedef unsigned int SORT_39;  // BV with 15 bits
  const SORT_39 mask_SORT_39 = (SORT_39)-1 >> (sizeof(SORT_39) * 8 - 15);
  const SORT_39 msb_SORT_39 = (SORT_39)1 << (15 - 1);
  typedef unsigned int SORT_53;  // BV with 17 bits
  const SORT_53 mask_SORT_53 = (SORT_53)-1 >> (sizeof(SORT_53) * 8 - 17);
  const SORT_53 msb_SORT_53 = (SORT_53)1 << (17 - 1);
  typedef unsigned int SORT_55;  // BV with 3 bits
  const SORT_55 mask_SORT_55 = (SORT_55)-1 >> (sizeof(SORT_55) * 8 - 3);
  const SORT_55 msb_SORT_55 = (SORT_55)1 << (3 - 1);
  typedef unsigned int SORT_110;  // BV with 9 bits
  const SORT_110 mask_SORT_110 = (SORT_110)-1 >> (sizeof(SORT_110) * 8 - 9);
  const SORT_110 msb_SORT_110 = (SORT_110)1 << (9 - 1);
  typedef unsigned int SORT_128;  // BV with 31 bits
  const SORT_128 mask_SORT_128 = (SORT_128)-1 >> (sizeof(SORT_128) * 8 - 31);
  const SORT_128 msb_SORT_128 = (SORT_128)1 << (31 - 1);
  typedef unsigned int SORT_260;  // BV with 4 bits
  const SORT_260 mask_SORT_260 = (SORT_260)-1 >> (sizeof(SORT_260) * 8 - 4);
  const SORT_260 msb_SORT_260 = (SORT_260)1 << (4 - 1);
  // Initializing constants ...
  const SORT_14 var_21 = 0;
  const SORT_20 var_32 = 3;
  const SORT_20 var_43 = 2;
  const SORT_14 var_48 = 1;
  const SORT_55 var_56 = 5;
  const SORT_20 var_187 = 0;
  const SORT_55 var_256 = 7;
  const SORT_260 var_261 = 8;
  const SORT_260 var_263 = 14;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_1 input_3;
  SORT_1 input_4;
  SORT_1 input_5;
  SORT_1 input_6;
  SORT_1 input_7;
  SORT_1 input_8;
  SORT_1 input_9;
  SORT_1 input_10;
  SORT_1 input_11;
  SORT_1 input_12;
  SORT_1 input_13;
  SORT_14 input_15;
  SORT_1 input_16;
  SORT_1 input_17;
  SORT_1 input_18;
  SORT_1 input_19;
  SORT_1 input_52;
  SORT_1 input_81;
  SORT_1 input_92;
  // Collecting state declarations ...
  // Initializing states ...
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_int();
    input_2 = input_2 & mask_SORT_1;
    input_3 = __VERIFIER_nondet_int();
    input_3 = input_3 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_int();
    input_4 = input_4 & mask_SORT_1;
    input_5 = __VERIFIER_nondet_int();
    input_5 = input_5 & mask_SORT_1;
    input_6 = __VERIFIER_nondet_int();
    input_6 = input_6 & mask_SORT_1;
    input_7 = __VERIFIER_nondet_int();
    input_7 = input_7 & mask_SORT_1;
    input_8 = __VERIFIER_nondet_int();
    input_8 = input_8 & mask_SORT_1;
    input_9 = __VERIFIER_nondet_int();
    input_9 = input_9 & mask_SORT_1;
    input_10 = __VERIFIER_nondet_int();
    input_10 = input_10 & mask_SORT_1;
    input_11 = __VERIFIER_nondet_int();
    input_11 = input_11 & mask_SORT_1;
    input_12 = __VERIFIER_nondet_int();
    input_12 = input_12 & mask_SORT_1;
    input_13 = __VERIFIER_nondet_int();
    input_13 = input_13 & mask_SORT_1;
    input_15 = __VERIFIER_nondet_int();
    input_15 = input_15 & mask_SORT_14;
    input_16 = __VERIFIER_nondet_int();
    input_16 = input_16 & mask_SORT_1;
    input_17 = __VERIFIER_nondet_int();
    input_17 = input_17 & mask_SORT_1;
    input_18 = __VERIFIER_nondet_int();
    input_18 = input_18 & mask_SORT_1;
    input_19 = __VERIFIER_nondet_int();
    input_19 = input_19 & mask_SORT_1;
    input_52 = __VERIFIER_nondet_int();
    input_52 = input_52 & mask_SORT_1;
    input_81 = __VERIFIER_nondet_int();
    input_81 = input_81 & mask_SORT_1;
    input_92 = __VERIFIER_nondet_int();
    input_92 = input_92 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_23_arg_0 = input_3;
    SORT_22 var_23 = var_23_arg_0 >> 0;
    var_23 = var_23 & mask_SORT_22;
    SORT_14 var_24_arg_0 = var_21;
    var_24_arg_0 = (var_24_arg_0 & msb_SORT_14) ? (var_24_arg_0 | ~mask_SORT_14) : (var_24_arg_0 & mask_SORT_14);
    SORT_22 var_24 = (int)var_24_arg_0;
    var_24 = var_24 & mask_SORT_22;
    SORT_22 var_25_arg_0 = var_23;
    var_25_arg_0 = (var_25_arg_0 & msb_SORT_22) ? (var_25_arg_0 | ~mask_SORT_22) : (var_25_arg_0 & mask_SORT_22);
    SORT_22 var_25_arg_1 = var_24;
    var_25_arg_1 = (var_25_arg_1 & msb_SORT_22) ? (var_25_arg_1 | ~mask_SORT_22) : (var_25_arg_1 & mask_SORT_22);
    SORT_14 var_25 = (int)var_25_arg_0 < (int)var_25_arg_1;
    SORT_14 var_26_arg_0 = var_25;
    SORT_14 var_26_arg_1 = var_21;
    SORT_20 var_26 = ((SORT_20)var_26_arg_0 << 1) | var_26_arg_1;
    SORT_1 var_27_arg_0 = input_12;
    SORT_14 var_27 = var_27_arg_0 >> 0;
    var_27 = var_27 & mask_SORT_14;
    SORT_1 var_28_arg_0 = input_3;
    SORT_14 var_28 = var_28_arg_0 >> 0;
    var_28 = var_28 & mask_SORT_14;
    SORT_14 var_29_arg_0 = var_27;
    SORT_14 var_29_arg_1 = var_28;
    SORT_14 var_29 = var_29_arg_0 | var_29_arg_1;
    var_29 = var_29 & mask_SORT_14;
    SORT_14 var_30_arg_0 = var_29;
    SORT_20 var_30 = var_30_arg_0;
    SORT_20 var_31_arg_0 = var_26;
    SORT_20 var_31_arg_1 = var_30;
    SORT_20 var_31 = var_31_arg_0 + var_31_arg_1;
    var_31 = var_31 & mask_SORT_20;
    SORT_20 var_77_arg_0 = var_31;
    SORT_14 var_77 = var_77_arg_0 != 0;
    SORT_14 var_78_arg_0 = var_77;
    SORT_14 var_78 = ~var_78_arg_0;
    var_78 = var_78 & mask_SORT_14;
    SORT_1 var_62_arg_0 = input_12;
    SORT_20 var_62 = var_62_arg_0 >> 7;
    var_62 = var_62 & mask_SORT_20;
    SORT_20 var_72_arg_0 = var_62;
    SORT_14 var_72 = var_72_arg_0 != 0;
    SORT_14 var_73_arg_0 = var_72;
    SORT_14 var_73 = ~var_73_arg_0;
    var_73 = var_73 & mask_SORT_14;
    SORT_14 var_69_arg_0 = var_48;
    SORT_20 var_69 = var_69_arg_0;
    SORT_20 var_70_arg_0 = var_62;
    SORT_20 var_70_arg_1 = var_69;
    SORT_14 var_70 = var_70_arg_0 == var_70_arg_1;
    SORT_1 var_68_arg_0 = input_3;
    SORT_1 var_68_arg_1 = input_5;
    SORT_1 var_68 = var_68_arg_0 - var_68_arg_1;
    var_68 = var_68 & mask_SORT_1;
    SORT_20 var_66_arg_0 = var_62;
    SORT_20 var_66_arg_1 = var_43;
    SORT_14 var_66 = var_66_arg_0 == var_66_arg_1;
    SORT_1 var_65_arg_0 = input_4;
    SORT_1 var_65_arg_1 = input_13;
    SORT_1 var_65 = var_65_arg_0 * var_65_arg_1;
    var_65 = var_65 & mask_SORT_1;
    SORT_20 var_63_arg_0 = var_62;
    SORT_20 var_63_arg_1 = var_32;
    SORT_14 var_63 = var_63_arg_0 == var_63_arg_1;
    SORT_1 var_54_arg_0 = input_3;
    var_54_arg_0 = (var_54_arg_0 & msb_SORT_1) ? (var_54_arg_0 | ~mask_SORT_1) : (var_54_arg_0 & mask_SORT_1);
    SORT_53 var_54 = (int)var_54_arg_0;
    var_54 = var_54 & mask_SORT_53;
    SORT_55 var_57_arg_0 = var_56;
    SORT_53 var_57 = var_57_arg_0;
    SORT_1 var_58_arg_0 = input_13;
    SORT_53 var_58 = var_58_arg_0;
    SORT_53 var_59_arg_0 = var_57;
    SORT_53 var_59_arg_1 = var_58;
    SORT_53 var_59 = var_59_arg_0 + var_59_arg_1;
    var_59 = var_59 & mask_SORT_53;
    SORT_53 var_60_arg_0 = var_54;
    SORT_53 var_60_arg_1 = var_59;
    SORT_53 var_60 = var_60_arg_0 << var_60_arg_1;
    var_60 = var_60 & mask_SORT_53;
    SORT_53 var_61_arg_0 = var_60;
    SORT_1 var_61 = var_61_arg_0 >> 0;
    var_61 = var_61 & mask_SORT_1;
    SORT_14 var_64_arg_0 = var_63;
    SORT_1 var_64_arg_1 = var_61;
    SORT_1 var_64_arg_2 = input_52;
    SORT_1 var_64 = var_64_arg_0 ? var_64_arg_1 : var_64_arg_2;
    SORT_14 var_67_arg_0 = var_66;
    SORT_1 var_67_arg_1 = var_65;
    SORT_1 var_67_arg_2 = var_64;
    SORT_1 var_67 = var_67_arg_0 ? var_67_arg_1 : var_67_arg_2;
    SORT_14 var_71_arg_0 = var_70;
    SORT_1 var_71_arg_1 = var_68;
    SORT_1 var_71_arg_2 = var_67;
    SORT_1 var_71 = var_71_arg_0 ? var_71_arg_1 : var_71_arg_2;
    SORT_14 var_74_arg_0 = var_73;
    SORT_1 var_74_arg_1 = input_6;
    SORT_1 var_74_arg_2 = var_71;
    SORT_1 var_74 = var_74_arg_0 ? var_74_arg_1 : var_74_arg_2;
    SORT_1 var_75_arg_0 = input_13;
    SORT_1 var_75_arg_1 = var_74;
    SORT_14 var_75 = var_75_arg_0 >= var_75_arg_1;
    SORT_14 var_76_arg_0 = var_75;
    SORT_1 var_76_arg_1 = input_18;
    SORT_1 var_76_arg_2 = input_2;
    SORT_1 var_76 = var_76_arg_0 ? var_76_arg_1 : var_76_arg_2;
    SORT_14 var_49_arg_0 = var_48;
    SORT_20 var_49 = var_49_arg_0;
    SORT_20 var_50_arg_0 = var_31;
    SORT_20 var_50_arg_1 = var_49;
    SORT_14 var_50 = var_50_arg_0 == var_50_arg_1;
    SORT_1 var_46_arg_0 = input_17;
    SORT_1 var_46_arg_1 = input_13;
    SORT_1 var_46 = var_46_arg_0 * var_46_arg_1;
    var_46 = var_46 & mask_SORT_1;
    SORT_1 var_47_arg_0 = var_46;
    SORT_1 var_47_arg_1 = input_9;
    SORT_1 var_47 = var_47_arg_0 + var_47_arg_1;
    var_47 = var_47 & mask_SORT_1;
    SORT_20 var_44_arg_0 = var_31;
    SORT_20 var_44_arg_1 = var_43;
    SORT_14 var_44 = var_44_arg_0 == var_44_arg_1;
    SORT_1 var_41_arg_0 = input_8;
    SORT_14 var_41 = var_41_arg_0 >> 0;
    var_41 = var_41 & mask_SORT_14;
    SORT_1 var_38_arg_0 = input_12;
    SORT_35 var_38 = var_38_arg_0 >> 8;
    var_38 = var_38 & mask_SORT_35;
    SORT_1 var_36_arg_0 = input_13;
    SORT_35 var_36 = var_36_arg_0 >> 1;
    var_36 = var_36 & mask_SORT_35;
    SORT_35 var_37_arg_0 = var_36;
    SORT_14 var_37_arg_1 = input_15;
    SORT_22 var_37 = ((SORT_22)var_37_arg_0 << 1) | var_37_arg_1;
    SORT_35 var_40_arg_0 = var_38;
    SORT_22 var_40_arg_1 = var_37;
    SORT_39 var_40 = ((SORT_39)var_40_arg_0 << 8) | var_40_arg_1;
    SORT_14 var_42_arg_0 = var_41;
    SORT_39 var_42_arg_1 = var_40;
    SORT_1 var_42 = ((SORT_1)var_42_arg_0 << 15) | var_42_arg_1;
    SORT_20 var_33_arg_0 = var_31;
    SORT_20 var_33_arg_1 = var_32;
    SORT_14 var_33 = var_33_arg_0 == var_33_arg_1;
    SORT_14 var_34_arg_0 = var_33;
    SORT_1 var_34_arg_1 = input_7;
    SORT_1 var_34_arg_2 = input_19;
    SORT_1 var_34 = var_34_arg_0 ? var_34_arg_1 : var_34_arg_2;
    SORT_14 var_45_arg_0 = var_44;
    SORT_1 var_45_arg_1 = var_42;
    SORT_1 var_45_arg_2 = var_34;
    SORT_1 var_45 = var_45_arg_0 ? var_45_arg_1 : var_45_arg_2;
    SORT_14 var_51_arg_0 = var_50;
    SORT_1 var_51_arg_1 = var_47;
    SORT_1 var_51_arg_2 = var_45;
    SORT_1 var_51 = var_51_arg_0 ? var_51_arg_1 : var_51_arg_2;
    SORT_14 var_79_arg_0 = var_78;
    SORT_1 var_79_arg_1 = var_76;
    SORT_1 var_79_arg_2 = var_51;
    SORT_1 var_79 = var_79_arg_0 ? var_79_arg_1 : var_79_arg_2;
    SORT_1 var_93_arg_0 = input_3;
    SORT_53 var_93 = var_93_arg_0;
    SORT_53 var_94_arg_0 = var_93;
    SORT_53 var_94_arg_1 = var_59;
    SORT_53 var_94 = var_94_arg_0 << var_94_arg_1;
    var_94 = var_94 & mask_SORT_53;
    SORT_53 var_95_arg_0 = var_94;
    SORT_1 var_95 = var_95_arg_0 >> 0;
    var_95 = var_95 & mask_SORT_1;
    SORT_14 var_96_arg_0 = var_63;
    SORT_1 var_96_arg_1 = var_95;
    SORT_1 var_96_arg_2 = input_92;
    SORT_1 var_96 = var_96_arg_0 ? var_96_arg_1 : var_96_arg_2;
    SORT_14 var_97_arg_0 = var_66;
    SORT_1 var_97_arg_1 = var_65;
    SORT_1 var_97_arg_2 = var_96;
    SORT_1 var_97 = var_97_arg_0 ? var_97_arg_1 : var_97_arg_2;
    SORT_14 var_98_arg_0 = var_70;
    SORT_1 var_98_arg_1 = var_68;
    SORT_1 var_98_arg_2 = var_97;
    SORT_1 var_98 = var_98_arg_0 ? var_98_arg_1 : var_98_arg_2;
    SORT_14 var_99_arg_0 = var_73;
    SORT_1 var_99_arg_1 = input_6;
    SORT_1 var_99_arg_2 = var_98;
    SORT_1 var_99 = var_99_arg_0 ? var_99_arg_1 : var_99_arg_2;
    SORT_1 var_100_arg_0 = input_13;
    SORT_1 var_100_arg_1 = var_99;
    SORT_14 var_100 = var_100_arg_0 >= var_100_arg_1;
    SORT_14 var_101_arg_0 = var_100;
    SORT_1 var_101_arg_1 = input_18;
    SORT_1 var_101_arg_2 = input_2;
    SORT_1 var_101 = var_101_arg_0 ? var_101_arg_1 : var_101_arg_2;
    SORT_1 var_90_arg_0 = var_46;
    SORT_1 var_90_arg_1 = input_16;
    SORT_1 var_90 = var_90_arg_0 + var_90_arg_1;
    var_90 = var_90 & mask_SORT_1;
    SORT_1 var_87_arg_0 = input_11;
    SORT_14 var_87 = var_87_arg_0 >> 0;
    var_87 = var_87 & mask_SORT_14;
    SORT_1 var_85_arg_0 = input_12;
    SORT_35 var_85 = var_85_arg_0 >> 8;
    var_85 = var_85 & mask_SORT_35;
    SORT_1 var_83_arg_0 = input_13;
    SORT_35 var_83 = var_83_arg_0 >> 1;
    var_83 = var_83 & mask_SORT_35;
    SORT_35 var_84_arg_0 = var_83;
    SORT_14 var_84_arg_1 = input_15;
    SORT_22 var_84 = ((SORT_22)var_84_arg_0 << 1) | var_84_arg_1;
    SORT_35 var_86_arg_0 = var_85;
    SORT_22 var_86_arg_1 = var_84;
    SORT_39 var_86 = ((SORT_39)var_86_arg_0 << 8) | var_86_arg_1;
    SORT_14 var_88_arg_0 = var_87;
    SORT_39 var_88_arg_1 = var_86;
    SORT_1 var_88 = ((SORT_1)var_88_arg_0 << 15) | var_88_arg_1;
    SORT_14 var_82_arg_0 = var_33;
    SORT_1 var_82_arg_1 = input_10;
    SORT_1 var_82_arg_2 = input_81;
    SORT_1 var_82 = var_82_arg_0 ? var_82_arg_1 : var_82_arg_2;
    SORT_14 var_89_arg_0 = var_44;
    SORT_1 var_89_arg_1 = var_88;
    SORT_1 var_89_arg_2 = var_82;
    SORT_1 var_89 = var_89_arg_0 ? var_89_arg_1 : var_89_arg_2;
    SORT_14 var_91_arg_0 = var_50;
    SORT_1 var_91_arg_1 = var_90;
    SORT_1 var_91_arg_2 = var_89;
    SORT_1 var_91 = var_91_arg_0 ? var_91_arg_1 : var_91_arg_2;
    SORT_14 var_102_arg_0 = var_78;
    SORT_1 var_102_arg_1 = var_101;
    SORT_1 var_102_arg_2 = var_91;
    SORT_1 var_102 = var_102_arg_0 ? var_102_arg_1 : var_102_arg_2;
    SORT_1 var_104_arg_0 = var_79;
    SORT_1 var_104_arg_1 = var_102;
    SORT_14 var_104 = var_104_arg_0 == var_104_arg_1;
    SORT_14 var_105_arg_0 = var_104;
    SORT_14 var_105 = ~var_105_arg_0;
    var_105 = var_105 & mask_SORT_14;
    SORT_14 var_106_arg_0 = var_48;
    SORT_14 var_106_arg_1 = var_105;
    SORT_14 var_106 = var_106_arg_0 & var_106_arg_1;
    var_106 = var_106 & mask_SORT_14;
    SORT_14 bad_107_arg_0 = var_106;
    __VERIFIER_assert(!(bad_107_arg_0));
    // Computing next states ...
    // Assigning next states ...
  }
}
