// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module main.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned short SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned short SORT_3;  // BV with 8 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 8);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (8 - 1);
  typedef unsigned short SORT_11;  // BV with 4 bits
  const SORT_11 mask_SORT_11 = (SORT_11)-1 >> (sizeof(SORT_11) * 8 - 4);
  const SORT_11 msb_SORT_11 = (SORT_11)1 << (4 - 1);
  typedef unsigned short SORT_31;  // BV with 10 bits
  const SORT_31 mask_SORT_31 = (SORT_31)-1 >> (sizeof(SORT_31) * 8 - 10);
  const SORT_31 msb_SORT_31 = (SORT_31)1 << (10 - 1);
  typedef unsigned short SORT_35;  // BV with 2 bits
  const SORT_35 mask_SORT_35 = (SORT_35)-1 >> (sizeof(SORT_35) * 8 - 2);
  const SORT_35 msb_SORT_35 = (SORT_35)1 << (2 - 1);
  typedef unsigned short SORT_67;  // BV with 7 bits
  const SORT_67 mask_SORT_67 = (SORT_67)-1 >> (sizeof(SORT_67) * 8 - 7);
  const SORT_67 msb_SORT_67 = (SORT_67)1 << (7 - 1);
  // Initializing constants ...
  const SORT_1 var_7 = 0;
  const SORT_11 var_12 = 0;
  const SORT_31 var_32 = 0;
  const SORT_1 var_39 = 1;
  const SORT_67 var_68 = 104;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_1 input_5;
  SORT_1 input_6;
  SORT_1 input_84;
  SORT_1 input_95;
  SORT_1 input_99;
  SORT_1 input_105;
  SORT_1 input_111;
  SORT_1 input_120;
  SORT_1 input_128;
  // Collecting state declarations ...
  SORT_1 state_8;
  SORT_11 state_13;
  SORT_1 state_16;
  SORT_1 state_19;
  SORT_1 state_22;
  SORT_1 state_25;
  SORT_1 state_28;
  SORT_31 state_33;
  SORT_1 state_43;
  SORT_1 state_45;
  SORT_1 state_47;
  SORT_1 state_49;
  SORT_1 state_51;
  SORT_1 state_53;
  SORT_1 state_55;
  SORT_1 state_57;
  SORT_1 state_59;
  SORT_1 state_61;
  // Initializing states ...
  SORT_1 init_9_arg_1 = var_7;
  state_8 = init_9_arg_1;
  SORT_11 init_14_arg_1 = var_12;
  state_13 = init_14_arg_1;
  SORT_1 init_17_arg_1 = var_7;
  state_16 = init_17_arg_1;
  SORT_1 init_20_arg_1 = var_7;
  state_19 = init_20_arg_1;
  SORT_1 init_23_arg_1 = var_7;
  state_22 = init_23_arg_1;
  SORT_1 init_26_arg_1 = var_7;
  state_25 = init_26_arg_1;
  SORT_1 init_29_arg_1 = var_7;
  state_28 = init_29_arg_1;
  SORT_31 init_34_arg_1 = var_32;
  state_33 = init_34_arg_1;
  SORT_1 init_44_arg_1 = var_7;
  state_43 = init_44_arg_1;
  SORT_1 init_46_arg_1 = var_7;
  state_45 = init_46_arg_1;
  SORT_1 init_48_arg_1 = var_7;
  state_47 = init_48_arg_1;
  SORT_1 init_50_arg_1 = var_7;
  state_49 = init_50_arg_1;
  SORT_1 init_52_arg_1 = var_39;
  state_51 = init_52_arg_1;
  SORT_1 init_54_arg_1 = var_7;
  state_53 = init_54_arg_1;
  SORT_1 init_56_arg_1 = var_7;
  state_55 = init_56_arg_1;
  SORT_1 init_58_arg_1 = var_7;
  state_57 = init_58_arg_1;
  SORT_1 init_60_arg_1 = var_7;
  state_59 = init_60_arg_1;
  SORT_1 init_62_arg_1 = var_7;
  state_61 = init_62_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_short();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_short();
    input_4 = input_4 & mask_SORT_3;
    input_5 = __VERIFIER_nondet_short();
    input_5 = input_5 & mask_SORT_1;
    input_6 = __VERIFIER_nondet_short();
    input_6 = input_6 & mask_SORT_1;
    input_84 = __VERIFIER_nondet_short();
    input_84 = input_84 & mask_SORT_1;
    input_95 = __VERIFIER_nondet_short();
    input_95 = input_95 & mask_SORT_1;
    input_99 = __VERIFIER_nondet_short();
    input_99 = input_99 & mask_SORT_1;
    input_105 = __VERIFIER_nondet_short();
    input_105 = input_105 & mask_SORT_1;
    input_111 = __VERIFIER_nondet_short();
    input_111 = input_111 & mask_SORT_1;
    input_120 = __VERIFIER_nondet_short();
    input_120 = input_120 & mask_SORT_1;
    input_128 = __VERIFIER_nondet_short();
    input_128 = input_128 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_31 var_36_arg_0 = state_33;
    SORT_35 var_36 = var_36_arg_0 >> 8;
    var_36 = var_36 & mask_SORT_35;
    SORT_35 var_37_arg_0 = var_36;
    SORT_1 var_37 = var_37_arg_0 != 0;
    SORT_1 var_38_arg_0 = var_37;
    SORT_1 var_38 = ~var_38_arg_0;
    var_38 = var_38 & mask_SORT_1;
    SORT_1 var_40_arg_0 = var_38;
    SORT_1 var_40 = ~var_40_arg_0;
    var_40 = var_40 & mask_SORT_1;
    SORT_1 var_41_arg_0 = var_39;
    SORT_1 var_41_arg_1 = var_40;
    SORT_1 var_41 = var_41_arg_0 & var_41_arg_1;
    var_41 = var_41 & mask_SORT_1;
    SORT_1 bad_42_arg_0 = var_41;
    __VERIFIER_assert(!(bad_42_arg_0));
    // Computing next states ...
    SORT_1 next_64_arg_1 = state_8;
    SORT_11 next_65_arg_1 = state_13;
    SORT_67 var_69_arg_0 = var_68;
    SORT_31 var_69 = var_69_arg_0;
    SORT_31 var_70_arg_0 = state_33;
    SORT_31 var_70_arg_1 = var_69;
    SORT_1 var_70 = var_70_arg_0 > var_70_arg_1;
    SORT_1 var_66_arg_0 = state_51;
    SORT_1 var_66_arg_1 = var_7;
    SORT_1 var_66_arg_2 = var_39;
    SORT_1 var_66 = var_66_arg_0 ? var_66_arg_1 : var_66_arg_2;
    SORT_1 var_71_arg_0 = var_70;
    SORT_1 var_71_arg_1 = var_66;
    SORT_1 var_71_arg_2 = var_39;
    SORT_1 var_71 = var_71_arg_0 ? var_71_arg_1 : var_71_arg_2;
    SORT_1 var_72_arg_0 = state_57;
    SORT_1 var_72_arg_1 = var_71;
    SORT_1 var_72_arg_2 = var_39;
    SORT_1 var_72 = var_72_arg_0 ? var_72_arg_1 : var_72_arg_2;
    SORT_1 next_73_arg_1 = var_72;
    SORT_1 var_76_arg_0 = state_49;
    SORT_1 var_76_arg_1 = var_39;
    SORT_1 var_76_arg_2 = state_61;
    SORT_1 var_76 = var_76_arg_0 ? var_76_arg_1 : var_76_arg_2;
    SORT_1 var_77_arg_0 = var_76;
    SORT_1 var_77 = ~var_77_arg_0;
    var_77 = var_77 & mask_SORT_1;
    SORT_1 var_78_arg_0 = input_5;
    SORT_1 var_78 = ~var_78_arg_0;
    var_78 = var_78 & mask_SORT_1;
    SORT_1 var_79_arg_0 = var_77;
    SORT_1 var_79_arg_1 = var_78;
    SORT_1 var_79 = var_79_arg_0 | var_79_arg_1;
    var_79 = var_79 & mask_SORT_1;
    SORT_1 var_80_arg_0 = var_79;
    SORT_1 var_80_arg_1 = var_39;
    SORT_1 var_80_arg_2 = var_7;
    SORT_1 var_80 = var_80_arg_0 ? var_80_arg_1 : var_80_arg_2;
    SORT_1 var_74_arg_0 = state_61;
    SORT_1 var_74_arg_1 = var_39;
    SORT_1 var_74_arg_2 = var_7;
    SORT_1 var_74 = var_74_arg_0 ? var_74_arg_1 : var_74_arg_2;
    SORT_1 var_75_arg_0 = state_49;
    SORT_1 var_75_arg_1 = var_74;
    SORT_1 var_75_arg_2 = state_19;
    SORT_1 var_75 = var_75_arg_0 ? var_75_arg_1 : var_75_arg_2;
    SORT_1 var_81_arg_0 = state_53;
    SORT_1 var_81_arg_1 = var_80;
    SORT_1 var_81_arg_2 = var_75;
    SORT_1 var_81 = var_81_arg_0 ? var_81_arg_1 : var_81_arg_2;
    SORT_1 next_82_arg_1 = var_81;
    SORT_1 next_83_arg_1 = state_22;
    SORT_1 var_86_arg_0 = state_43;
    SORT_1 var_86 = ~var_86_arg_0;
    var_86 = var_86 & mask_SORT_1;
    SORT_1 var_85_arg_0 = state_43;
    SORT_1 var_85_arg_1 = state_25;
    SORT_1 var_85_arg_2 = input_84;
    SORT_1 var_85 = var_85_arg_0 ? var_85_arg_1 : var_85_arg_2;
    SORT_1 var_87_arg_0 = var_86;
    SORT_1 var_87_arg_1 = var_39;
    SORT_1 var_87_arg_2 = var_85;
    SORT_1 var_87 = var_87_arg_0 ? var_87_arg_1 : var_87_arg_2;
    SORT_1 next_88_arg_1 = var_87;
    SORT_1 next_89_arg_1 = state_28;
    SORT_1 var_90_arg_0 = var_39;
    SORT_31 var_90 = var_90_arg_0;
    SORT_31 var_91_arg_0 = state_33;
    SORT_31 var_91_arg_1 = var_90;
    SORT_31 var_91 = var_91_arg_0 + var_91_arg_1;
    var_91 = var_91 & mask_SORT_31;
    SORT_1 var_92_arg_0 = var_70;
    SORT_31 var_92_arg_1 = var_32;
    SORT_31 var_92_arg_2 = var_91;
    SORT_31 var_92 = var_92_arg_0 ? var_92_arg_1 : var_92_arg_2;
    SORT_1 var_93_arg_0 = state_57;
    SORT_31 var_93_arg_1 = var_92;
    SORT_31 var_93_arg_2 = state_33;
    SORT_31 var_93 = var_93_arg_0 ? var_93_arg_1 : var_93_arg_2;
    SORT_31 next_94_arg_1 = var_93;
    SORT_1 var_96_arg_0 = state_43;
    SORT_1 var_96_arg_1 = var_7;
    SORT_1 var_96_arg_2 = input_95;
    SORT_1 var_96 = var_96_arg_0 ? var_96_arg_1 : var_96_arg_2;
    SORT_1 var_97_arg_0 = var_86;
    SORT_1 var_97_arg_1 = var_39;
    SORT_1 var_97_arg_2 = var_96;
    SORT_1 var_97 = var_97_arg_0 ? var_97_arg_1 : var_97_arg_2;
    SORT_1 next_98_arg_1 = var_97;
    SORT_1 var_102_arg_0 = state_45;
    SORT_1 var_102 = ~var_102_arg_0;
    var_102 = var_102 & mask_SORT_1;
    SORT_1 var_101_arg_0 = state_55;
    SORT_1 var_101_arg_1 = var_39;
    SORT_1 var_101_arg_2 = var_7;
    SORT_1 var_101 = var_101_arg_0 ? var_101_arg_1 : var_101_arg_2;
    SORT_1 var_100_arg_0 = state_45;
    SORT_1 var_100_arg_1 = var_7;
    SORT_1 var_100_arg_2 = input_99;
    SORT_1 var_100 = var_100_arg_0 ? var_100_arg_1 : var_100_arg_2;
    SORT_1 var_103_arg_0 = var_102;
    SORT_1 var_103_arg_1 = var_101;
    SORT_1 var_103_arg_2 = var_100;
    SORT_1 var_103 = var_103_arg_0 ? var_103_arg_1 : var_103_arg_2;
    SORT_1 next_104_arg_1 = var_103;
    SORT_1 var_108_arg_0 = state_47;
    SORT_1 var_108 = ~var_108_arg_0;
    var_108 = var_108 & mask_SORT_1;
    SORT_1 var_107_arg_0 = state_59;
    SORT_1 var_107_arg_1 = var_39;
    SORT_1 var_107_arg_2 = var_7;
    SORT_1 var_107 = var_107_arg_0 ? var_107_arg_1 : var_107_arg_2;
    SORT_1 var_106_arg_0 = state_47;
    SORT_1 var_106_arg_1 = var_7;
    SORT_1 var_106_arg_2 = input_105;
    SORT_1 var_106 = var_106_arg_0 ? var_106_arg_1 : var_106_arg_2;
    SORT_1 var_109_arg_0 = var_108;
    SORT_1 var_109_arg_1 = var_107;
    SORT_1 var_109_arg_2 = var_106;
    SORT_1 var_109 = var_109_arg_0 ? var_109_arg_1 : var_109_arg_2;
    SORT_1 next_110_arg_1 = var_109;
    SORT_1 var_113_arg_0 = state_59;
    SORT_1 var_113_arg_1 = var_39;
    SORT_1 var_113_arg_2 = state_49;
    SORT_1 var_113 = var_113_arg_0 ? var_113_arg_1 : var_113_arg_2;
    SORT_1 var_112_arg_0 = state_47;
    SORT_1 var_112_arg_1 = var_7;
    SORT_1 var_112_arg_2 = input_111;
    SORT_1 var_112 = var_112_arg_0 ? var_112_arg_1 : var_112_arg_2;
    SORT_1 var_114_arg_0 = var_108;
    SORT_1 var_114_arg_1 = var_113;
    SORT_1 var_114_arg_2 = var_112;
    SORT_1 var_114 = var_114_arg_0 ? var_114_arg_1 : var_114_arg_2;
    SORT_1 next_115_arg_1 = var_114;
    SORT_1 var_116_arg_0 = state_51;
    SORT_1 var_116_arg_1 = var_39;
    SORT_1 var_116_arg_2 = var_7;
    SORT_1 var_116 = var_116_arg_0 ? var_116_arg_1 : var_116_arg_2;
    SORT_1 var_117_arg_0 = var_70;
    SORT_1 var_117_arg_1 = var_116;
    SORT_1 var_117_arg_2 = state_51;
    SORT_1 var_117 = var_117_arg_0 ? var_117_arg_1 : var_117_arg_2;
    SORT_1 var_118_arg_0 = state_57;
    SORT_1 var_118_arg_1 = var_117;
    SORT_1 var_118_arg_2 = state_51;
    SORT_1 var_118 = var_118_arg_0 ? var_118_arg_1 : var_118_arg_2;
    SORT_1 next_119_arg_1 = var_118;
    SORT_1 var_121_arg_0 = state_47;
    SORT_1 var_121_arg_1 = var_39;
    SORT_1 var_121_arg_2 = input_120;
    SORT_1 var_121 = var_121_arg_0 ? var_121_arg_1 : var_121_arg_2;
    SORT_1 var_122_arg_0 = var_108;
    SORT_1 var_122_arg_1 = state_53;
    SORT_1 var_122_arg_2 = var_121;
    SORT_1 var_122 = var_122_arg_0 ? var_122_arg_1 : var_122_arg_2;
    SORT_1 next_123_arg_1 = var_122;
    SORT_1 next_124_arg_1 = state_55;
    SORT_1 var_125_arg_0 = var_79;
    SORT_1 var_125_arg_1 = state_57;
    SORT_1 var_125_arg_2 = var_39;
    SORT_1 var_125 = var_125_arg_0 ? var_125_arg_1 : var_125_arg_2;
    SORT_1 var_126_arg_0 = state_53;
    SORT_1 var_126_arg_1 = var_125;
    SORT_1 var_126_arg_2 = state_57;
    SORT_1 var_126 = var_126_arg_0 ? var_126_arg_1 : var_126_arg_2;
    SORT_1 next_127_arg_1 = var_126;
    SORT_1 var_129_arg_0 = state_45;
    SORT_1 var_129_arg_1 = var_39;
    SORT_1 var_129_arg_2 = input_128;
    SORT_1 var_129 = var_129_arg_0 ? var_129_arg_1 : var_129_arg_2;
    SORT_1 var_130_arg_0 = var_102;
    SORT_1 var_130_arg_1 = state_59;
    SORT_1 var_130_arg_2 = var_129;
    SORT_1 var_130 = var_130_arg_0 ? var_130_arg_1 : var_130_arg_2;
    SORT_1 next_131_arg_1 = var_130;
    SORT_1 next_132_arg_1 = var_76;
    // Assigning next states ...
    state_8 = next_64_arg_1;
    state_13 = next_65_arg_1;
    state_16 = next_73_arg_1;
    state_19 = next_82_arg_1;
    state_22 = next_83_arg_1;
    state_25 = next_88_arg_1;
    state_28 = next_89_arg_1;
    state_33 = next_94_arg_1;
    state_43 = next_98_arg_1;
    state_45 = next_104_arg_1;
    state_47 = next_110_arg_1;
    state_49 = next_115_arg_1;
    state_51 = next_119_arg_1;
    state_53 = next_123_arg_1;
    state_55 = next_124_arg_1;
    state_57 = next_127_arg_1;
    state_59 = next_131_arg_1;
    state_61 = next_132_arg_1;
  }
}
