// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module main.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned short SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned short SORT_3;  // BV with 8 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 8);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (8 - 1);
  typedef unsigned short SORT_11;  // BV with 4 bits
  const SORT_11 mask_SORT_11 = (SORT_11)-1 >> (sizeof(SORT_11) * 8 - 4);
  const SORT_11 msb_SORT_11 = (SORT_11)1 << (4 - 1);
  typedef unsigned short SORT_58;  // BV with 10 bits
  const SORT_58 mask_SORT_58 = (SORT_58)-1 >> (sizeof(SORT_58) * 8 - 10);
  const SORT_58 msb_SORT_58 = (SORT_58)1 << (10 - 1);
  typedef unsigned short SORT_66;  // BV with 7 bits
  const SORT_66 mask_SORT_66 = (SORT_66)-1 >> (sizeof(SORT_66) * 8 - 7);
  const SORT_66 msb_SORT_66 = (SORT_66)1 << (7 - 1);
  // Initializing constants ...
  const SORT_1 var_7 = 0;
  const SORT_11 var_12 = 0;
  const SORT_1 var_38 = 1;
  const SORT_58 var_59 = 0;
  const SORT_66 var_67 = 104;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_1 input_5;
  SORT_1 input_6;
  SORT_1 input_83;
  SORT_1 input_89;
  SORT_1 input_95;
  SORT_1 input_99;
  SORT_1 input_103;
  SORT_1 input_109;
  SORT_1 input_122;
  // Collecting state declarations ...
  SORT_1 state_8;
  SORT_11 state_13;
  SORT_1 state_16;
  SORT_1 state_19;
  SORT_1 state_22;
  SORT_1 state_25;
  SORT_1 state_28;
  SORT_1 state_31;
  SORT_1 state_34;
  SORT_1 state_42;
  SORT_1 state_44;
  SORT_1 state_46;
  SORT_1 state_48;
  SORT_1 state_50;
  SORT_1 state_52;
  SORT_1 state_54;
  SORT_1 state_56;
  SORT_58 state_60;
  // Initializing states ...
  SORT_1 init_9_arg_1 = var_7;
  state_8 = init_9_arg_1;
  SORT_11 init_14_arg_1 = var_12;
  state_13 = init_14_arg_1;
  SORT_1 init_17_arg_1 = var_7;
  state_16 = init_17_arg_1;
  SORT_1 init_20_arg_1 = var_7;
  state_19 = init_20_arg_1;
  SORT_1 init_23_arg_1 = var_7;
  state_22 = init_23_arg_1;
  SORT_1 init_26_arg_1 = var_7;
  state_25 = init_26_arg_1;
  SORT_1 init_29_arg_1 = var_7;
  state_28 = init_29_arg_1;
  SORT_1 init_32_arg_1 = var_7;
  state_31 = init_32_arg_1;
  SORT_1 init_35_arg_1 = var_7;
  state_34 = init_35_arg_1;
  SORT_1 init_43_arg_1 = var_7;
  state_42 = init_43_arg_1;
  SORT_1 init_45_arg_1 = var_7;
  state_44 = init_45_arg_1;
  SORT_1 init_47_arg_1 = var_7;
  state_46 = init_47_arg_1;
  SORT_1 init_49_arg_1 = var_38;
  state_48 = init_49_arg_1;
  SORT_1 init_51_arg_1 = var_7;
  state_50 = init_51_arg_1;
  SORT_1 init_53_arg_1 = var_7;
  state_52 = init_53_arg_1;
  SORT_1 init_55_arg_1 = var_7;
  state_54 = init_55_arg_1;
  SORT_1 init_57_arg_1 = var_7;
  state_56 = init_57_arg_1;
  SORT_58 init_61_arg_1 = var_59;
  state_60 = init_61_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_short();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_short();
    input_4 = input_4 & mask_SORT_3;
    input_5 = __VERIFIER_nondet_short();
    input_5 = input_5 & mask_SORT_1;
    input_6 = __VERIFIER_nondet_short();
    input_6 = input_6 & mask_SORT_1;
    input_83 = __VERIFIER_nondet_short();
    input_83 = input_83 & mask_SORT_1;
    input_89 = __VERIFIER_nondet_short();
    input_89 = input_89 & mask_SORT_1;
    input_95 = __VERIFIER_nondet_short();
    input_95 = input_95 & mask_SORT_1;
    input_99 = __VERIFIER_nondet_short();
    input_99 = input_99 & mask_SORT_1;
    input_103 = __VERIFIER_nondet_short();
    input_103 = input_103 & mask_SORT_1;
    input_109 = __VERIFIER_nondet_short();
    input_109 = input_109 & mask_SORT_1;
    input_122 = __VERIFIER_nondet_short();
    input_122 = input_122 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_33_arg_0 = state_31;
    SORT_1 var_33 = ~var_33_arg_0;
    var_33 = var_33 & mask_SORT_1;
    SORT_1 var_36_arg_0 = state_34;
    SORT_1 var_36 = ~var_36_arg_0;
    var_36 = var_36 & mask_SORT_1;
    SORT_1 var_37_arg_0 = var_33;
    SORT_1 var_37_arg_1 = var_36;
    SORT_1 var_37 = var_37_arg_0 | var_37_arg_1;
    var_37 = var_37 & mask_SORT_1;
    SORT_1 var_39_arg_0 = var_37;
    SORT_1 var_39 = ~var_39_arg_0;
    var_39 = var_39 & mask_SORT_1;
    SORT_1 var_40_arg_0 = var_38;
    SORT_1 var_40_arg_1 = var_39;
    SORT_1 var_40 = var_40_arg_0 & var_40_arg_1;
    var_40 = var_40 & mask_SORT_1;
    SORT_1 bad_41_arg_0 = var_40;
    __VERIFIER_assert(!(bad_41_arg_0));
    // Computing next states ...
    SORT_1 next_63_arg_1 = state_8;
    SORT_11 next_64_arg_1 = state_13;
    SORT_66 var_68_arg_0 = var_67;
    SORT_58 var_68 = var_68_arg_0;
    SORT_58 var_69_arg_0 = state_60;
    SORT_58 var_69_arg_1 = var_68;
    SORT_1 var_69 = var_69_arg_0 > var_69_arg_1;
    SORT_1 var_65_arg_0 = state_48;
    SORT_1 var_65_arg_1 = var_7;
    SORT_1 var_65_arg_2 = var_38;
    SORT_1 var_65 = var_65_arg_0 ? var_65_arg_1 : var_65_arg_2;
    SORT_1 var_70_arg_0 = var_69;
    SORT_1 var_70_arg_1 = var_65;
    SORT_1 var_70_arg_2 = var_38;
    SORT_1 var_70 = var_70_arg_0 ? var_70_arg_1 : var_70_arg_2;
    SORT_1 var_71_arg_0 = state_52;
    SORT_1 var_71_arg_1 = var_70;
    SORT_1 var_71_arg_2 = var_38;
    SORT_1 var_71 = var_71_arg_0 ? var_71_arg_1 : var_71_arg_2;
    SORT_1 next_72_arg_1 = var_71;
    SORT_1 var_75_arg_0 = state_31;
    SORT_1 var_75_arg_1 = var_38;
    SORT_1 var_75_arg_2 = state_56;
    SORT_1 var_75 = var_75_arg_0 ? var_75_arg_1 : var_75_arg_2;
    SORT_1 var_76_arg_0 = var_75;
    SORT_1 var_76 = ~var_76_arg_0;
    var_76 = var_76 & mask_SORT_1;
    SORT_1 var_77_arg_0 = input_5;
    SORT_1 var_77 = ~var_77_arg_0;
    var_77 = var_77 & mask_SORT_1;
    SORT_1 var_78_arg_0 = var_76;
    SORT_1 var_78_arg_1 = var_77;
    SORT_1 var_78 = var_78_arg_0 | var_78_arg_1;
    var_78 = var_78 & mask_SORT_1;
    SORT_1 var_79_arg_0 = var_78;
    SORT_1 var_79_arg_1 = var_38;
    SORT_1 var_79_arg_2 = var_7;
    SORT_1 var_79 = var_79_arg_0 ? var_79_arg_1 : var_79_arg_2;
    SORT_1 var_73_arg_0 = state_56;
    SORT_1 var_73_arg_1 = var_38;
    SORT_1 var_73_arg_2 = var_7;
    SORT_1 var_73 = var_73_arg_0 ? var_73_arg_1 : var_73_arg_2;
    SORT_1 var_74_arg_0 = state_31;
    SORT_1 var_74_arg_1 = var_73;
    SORT_1 var_74_arg_2 = state_19;
    SORT_1 var_74 = var_74_arg_0 ? var_74_arg_1 : var_74_arg_2;
    SORT_1 var_80_arg_0 = state_34;
    SORT_1 var_80_arg_1 = var_79;
    SORT_1 var_80_arg_2 = var_74;
    SORT_1 var_80 = var_80_arg_0 ? var_80_arg_1 : var_80_arg_2;
    SORT_1 next_81_arg_1 = var_80;
    SORT_1 next_82_arg_1 = state_22;
    SORT_1 var_85_arg_0 = state_42;
    SORT_1 var_85 = ~var_85_arg_0;
    var_85 = var_85 & mask_SORT_1;
    SORT_1 var_84_arg_0 = state_42;
    SORT_1 var_84_arg_1 = state_25;
    SORT_1 var_84_arg_2 = input_83;
    SORT_1 var_84 = var_84_arg_0 ? var_84_arg_1 : var_84_arg_2;
    SORT_1 var_86_arg_0 = var_85;
    SORT_1 var_86_arg_1 = var_38;
    SORT_1 var_86_arg_2 = var_84;
    SORT_1 var_86 = var_86_arg_0 ? var_86_arg_1 : var_86_arg_2;
    SORT_1 next_87_arg_1 = var_86;
    SORT_1 next_88_arg_1 = state_28;
    SORT_1 var_92_arg_0 = state_46;
    SORT_1 var_92 = ~var_92_arg_0;
    var_92 = var_92 & mask_SORT_1;
    SORT_1 var_91_arg_0 = state_54;
    SORT_1 var_91_arg_1 = var_38;
    SORT_1 var_91_arg_2 = state_31;
    SORT_1 var_91 = var_91_arg_0 ? var_91_arg_1 : var_91_arg_2;
    SORT_1 var_90_arg_0 = state_46;
    SORT_1 var_90_arg_1 = var_7;
    SORT_1 var_90_arg_2 = input_89;
    SORT_1 var_90 = var_90_arg_0 ? var_90_arg_1 : var_90_arg_2;
    SORT_1 var_93_arg_0 = var_92;
    SORT_1 var_93_arg_1 = var_91;
    SORT_1 var_93_arg_2 = var_90;
    SORT_1 var_93 = var_93_arg_0 ? var_93_arg_1 : var_93_arg_2;
    SORT_1 next_94_arg_1 = var_93;
    SORT_1 var_96_arg_0 = state_46;
    SORT_1 var_96_arg_1 = var_38;
    SORT_1 var_96_arg_2 = input_95;
    SORT_1 var_96 = var_96_arg_0 ? var_96_arg_1 : var_96_arg_2;
    SORT_1 var_97_arg_0 = var_92;
    SORT_1 var_97_arg_1 = state_34;
    SORT_1 var_97_arg_2 = var_96;
    SORT_1 var_97 = var_97_arg_0 ? var_97_arg_1 : var_97_arg_2;
    SORT_1 next_98_arg_1 = var_97;
    SORT_1 var_100_arg_0 = state_42;
    SORT_1 var_100_arg_1 = var_7;
    SORT_1 var_100_arg_2 = input_99;
    SORT_1 var_100 = var_100_arg_0 ? var_100_arg_1 : var_100_arg_2;
    SORT_1 var_101_arg_0 = var_85;
    SORT_1 var_101_arg_1 = var_38;
    SORT_1 var_101_arg_2 = var_100;
    SORT_1 var_101 = var_101_arg_0 ? var_101_arg_1 : var_101_arg_2;
    SORT_1 next_102_arg_1 = var_101;
    SORT_1 var_106_arg_0 = state_44;
    SORT_1 var_106 = ~var_106_arg_0;
    var_106 = var_106 & mask_SORT_1;
    SORT_1 var_105_arg_0 = state_50;
    SORT_1 var_105_arg_1 = var_38;
    SORT_1 var_105_arg_2 = var_7;
    SORT_1 var_105 = var_105_arg_0 ? var_105_arg_1 : var_105_arg_2;
    SORT_1 var_104_arg_0 = state_44;
    SORT_1 var_104_arg_1 = var_7;
    SORT_1 var_104_arg_2 = input_103;
    SORT_1 var_104 = var_104_arg_0 ? var_104_arg_1 : var_104_arg_2;
    SORT_1 var_107_arg_0 = var_106;
    SORT_1 var_107_arg_1 = var_105;
    SORT_1 var_107_arg_2 = var_104;
    SORT_1 var_107 = var_107_arg_0 ? var_107_arg_1 : var_107_arg_2;
    SORT_1 next_108_arg_1 = var_107;
    SORT_1 var_111_arg_0 = state_54;
    SORT_1 var_111_arg_1 = var_38;
    SORT_1 var_111_arg_2 = var_7;
    SORT_1 var_111 = var_111_arg_0 ? var_111_arg_1 : var_111_arg_2;
    SORT_1 var_110_arg_0 = state_46;
    SORT_1 var_110_arg_1 = var_7;
    SORT_1 var_110_arg_2 = input_109;
    SORT_1 var_110 = var_110_arg_0 ? var_110_arg_1 : var_110_arg_2;
    SORT_1 var_112_arg_0 = var_92;
    SORT_1 var_112_arg_1 = var_111;
    SORT_1 var_112_arg_2 = var_110;
    SORT_1 var_112 = var_112_arg_0 ? var_112_arg_1 : var_112_arg_2;
    SORT_1 next_113_arg_1 = var_112;
    SORT_1 var_114_arg_0 = state_48;
    SORT_1 var_114_arg_1 = var_38;
    SORT_1 var_114_arg_2 = var_7;
    SORT_1 var_114 = var_114_arg_0 ? var_114_arg_1 : var_114_arg_2;
    SORT_1 var_115_arg_0 = var_69;
    SORT_1 var_115_arg_1 = var_114;
    SORT_1 var_115_arg_2 = state_48;
    SORT_1 var_115 = var_115_arg_0 ? var_115_arg_1 : var_115_arg_2;
    SORT_1 var_116_arg_0 = state_52;
    SORT_1 var_116_arg_1 = var_115;
    SORT_1 var_116_arg_2 = state_48;
    SORT_1 var_116 = var_116_arg_0 ? var_116_arg_1 : var_116_arg_2;
    SORT_1 next_117_arg_1 = var_116;
    SORT_1 next_118_arg_1 = state_50;
    SORT_1 var_119_arg_0 = var_78;
    SORT_1 var_119_arg_1 = state_52;
    SORT_1 var_119_arg_2 = var_38;
    SORT_1 var_119 = var_119_arg_0 ? var_119_arg_1 : var_119_arg_2;
    SORT_1 var_120_arg_0 = state_34;
    SORT_1 var_120_arg_1 = var_119;
    SORT_1 var_120_arg_2 = state_52;
    SORT_1 var_120 = var_120_arg_0 ? var_120_arg_1 : var_120_arg_2;
    SORT_1 next_121_arg_1 = var_120;
    SORT_1 var_123_arg_0 = state_44;
    SORT_1 var_123_arg_1 = var_38;
    SORT_1 var_123_arg_2 = input_122;
    SORT_1 var_123 = var_123_arg_0 ? var_123_arg_1 : var_123_arg_2;
    SORT_1 var_124_arg_0 = var_106;
    SORT_1 var_124_arg_1 = state_54;
    SORT_1 var_124_arg_2 = var_123;
    SORT_1 var_124 = var_124_arg_0 ? var_124_arg_1 : var_124_arg_2;
    SORT_1 next_125_arg_1 = var_124;
    SORT_1 next_126_arg_1 = var_75;
    SORT_1 var_127_arg_0 = var_38;
    SORT_58 var_127 = var_127_arg_0;
    SORT_58 var_128_arg_0 = state_60;
    SORT_58 var_128_arg_1 = var_127;
    SORT_58 var_128 = var_128_arg_0 + var_128_arg_1;
    var_128 = var_128 & mask_SORT_58;
    SORT_1 var_129_arg_0 = var_69;
    SORT_58 var_129_arg_1 = var_59;
    SORT_58 var_129_arg_2 = var_128;
    SORT_58 var_129 = var_129_arg_0 ? var_129_arg_1 : var_129_arg_2;
    SORT_1 var_130_arg_0 = state_52;
    SORT_58 var_130_arg_1 = var_129;
    SORT_58 var_130_arg_2 = state_60;
    SORT_58 var_130 = var_130_arg_0 ? var_130_arg_1 : var_130_arg_2;
    SORT_58 next_131_arg_1 = var_130;
    // Assigning next states ...
    state_8 = next_63_arg_1;
    state_13 = next_64_arg_1;
    state_16 = next_72_arg_1;
    state_19 = next_81_arg_1;
    state_22 = next_82_arg_1;
    state_25 = next_87_arg_1;
    state_28 = next_88_arg_1;
    state_31 = next_94_arg_1;
    state_34 = next_98_arg_1;
    state_42 = next_102_arg_1;
    state_44 = next_108_arg_1;
    state_46 = next_113_arg_1;
    state_48 = next_117_arg_1;
    state_50 = next_118_arg_1;
    state_52 = next_121_arg_1;
    state_54 = next_125_arg_1;
    state_56 = next_126_arg_1;
    state_60 = next_131_arg_1;
  }
}
