// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module rotate.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned int SORT_1;  // BV with 5 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 5);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (5 - 1);
  typedef unsigned int SORT_3;  // BV with 1 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 1);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (1 - 1);
  typedef unsigned int SORT_5;  // BV with 32 bits
  const SORT_5 mask_SORT_5 = (SORT_5)-1 >> (sizeof(SORT_5) * 8 - 32);
  const SORT_5 msb_SORT_5 = (SORT_5)1 << (32 - 1);
  typedef unsigned int SORT_21;  // BV with 31 bits
  const SORT_21 mask_SORT_21 = (SORT_21)-1 >> (sizeof(SORT_21) * 8 - 31);
  const SORT_21 msb_SORT_21 = (SORT_21)1 << (31 - 1);
  typedef unsigned int SORT_28;  // BV with 30 bits
  const SORT_28 mask_SORT_28 = (SORT_28)-1 >> (sizeof(SORT_28) * 8 - 30);
  const SORT_28 msb_SORT_28 = (SORT_28)1 << (30 - 1);
  typedef unsigned int SORT_30;  // BV with 2 bits
  const SORT_30 mask_SORT_30 = (SORT_30)-1 >> (sizeof(SORT_30) * 8 - 2);
  const SORT_30 msb_SORT_30 = (SORT_30)1 << (2 - 1);
  typedef unsigned int SORT_36;  // BV with 28 bits
  const SORT_36 mask_SORT_36 = (SORT_36)-1 >> (sizeof(SORT_36) * 8 - 28);
  const SORT_36 msb_SORT_36 = (SORT_36)1 << (28 - 1);
  typedef unsigned int SORT_38;  // BV with 4 bits
  const SORT_38 mask_SORT_38 = (SORT_38)-1 >> (sizeof(SORT_38) * 8 - 4);
  const SORT_38 msb_SORT_38 = (SORT_38)1 << (4 - 1);
  typedef unsigned int SORT_44;  // BV with 24 bits
  const SORT_44 mask_SORT_44 = (SORT_44)-1 >> (sizeof(SORT_44) * 8 - 24);
  const SORT_44 msb_SORT_44 = (SORT_44)1 << (24 - 1);
  typedef unsigned int SORT_46;  // BV with 8 bits
  const SORT_46 mask_SORT_46 = (SORT_46)-1 >> (sizeof(SORT_46) * 8 - 8);
  const SORT_46 msb_SORT_46 = (SORT_46)1 << (8 - 1);
  typedef unsigned int SORT_52;  // BV with 16 bits
  const SORT_52 mask_SORT_52 = (SORT_52)-1 >> (sizeof(SORT_52) * 8 - 16);
  const SORT_52 msb_SORT_52 = (SORT_52)1 << (16 - 1);
  // Initializing constants ...
  const SORT_5 var_7 = 0;
  const SORT_5 var_11 = 2863311530;
  const SORT_3 var_14 = 1;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_5 input_6;
  // Collecting state declarations ...
  SORT_5 state_8;
  SORT_5 state_18;
  // Initializing states ...
  SORT_5 init_9_arg_1 = var_7;
  state_8 = init_9_arg_1;
  SORT_5 init_19_arg_1 = var_7;
  state_18 = init_19_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_int();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_int();
    input_4 = input_4 & mask_SORT_3;
    input_6 = __VERIFIER_nondet_int();
    input_6 = input_6 & mask_SORT_5;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_5 var_12_arg_0 = state_8;
    SORT_5 var_12_arg_1 = var_11;
    SORT_3 var_12 = var_12_arg_0 == var_12_arg_1;
    SORT_3 var_13_arg_0 = var_12;
    SORT_3 var_13 = ~var_13_arg_0;
    var_13 = var_13 & mask_SORT_3;
    SORT_3 var_15_arg_0 = var_13;
    SORT_3 var_15 = ~var_15_arg_0;
    var_15 = var_15 & mask_SORT_3;
    SORT_3 var_16_arg_0 = var_14;
    SORT_3 var_16_arg_1 = var_15;
    SORT_3 var_16 = var_16_arg_0 & var_16_arg_1;
    var_16 = var_16 & mask_SORT_3;
    SORT_3 bad_17_arg_0 = var_16;
    __VERIFIER_assert(!(bad_17_arg_0));
    // Computing next states ...
    SORT_1 var_56_arg_0 = input_2;
    SORT_3 var_56 = var_56_arg_0 >> 4;
    var_56 = var_56 & mask_SORT_3;
    SORT_1 var_49_arg_0 = input_2;
    SORT_3 var_49 = var_49_arg_0 >> 3;
    var_49 = var_49 & mask_SORT_3;
    SORT_1 var_41_arg_0 = input_2;
    SORT_3 var_41 = var_41_arg_0 >> 2;
    var_41 = var_41 & mask_SORT_3;
    SORT_1 var_33_arg_0 = input_2;
    SORT_3 var_33 = var_33_arg_0 >> 1;
    var_33 = var_33 & mask_SORT_3;
    SORT_1 var_25_arg_0 = input_2;
    SORT_3 var_25 = var_25_arg_0 >> 0;
    var_25 = var_25 & mask_SORT_3;
    SORT_5 var_23_arg_0 = state_18;
    SORT_3 var_23 = var_23_arg_0 >> 0;
    var_23 = var_23 & mask_SORT_3;
    SORT_5 var_22_arg_0 = state_18;
    SORT_21 var_22 = var_22_arg_0 >> 1;
    var_22 = var_22 & mask_SORT_21;
    SORT_3 var_24_arg_0 = var_23;
    SORT_21 var_24_arg_1 = var_22;
    SORT_5 var_24 = ((SORT_5)var_24_arg_0 << 31) | var_24_arg_1;
    SORT_3 var_26_arg_0 = var_25;
    SORT_5 var_26_arg_1 = var_24;
    SORT_5 var_26_arg_2 = state_18;
    SORT_5 var_26 = var_26_arg_0 ? var_26_arg_1 : var_26_arg_2;
    SORT_5 var_31_arg_0 = var_26;
    SORT_30 var_31 = var_31_arg_0 >> 0;
    var_31 = var_31 & mask_SORT_30;
    SORT_5 var_29_arg_0 = var_26;
    SORT_28 var_29 = var_29_arg_0 >> 2;
    var_29 = var_29 & mask_SORT_28;
    SORT_30 var_32_arg_0 = var_31;
    SORT_28 var_32_arg_1 = var_29;
    SORT_5 var_32 = ((SORT_5)var_32_arg_0 << 30) | var_32_arg_1;
    SORT_3 var_34_arg_0 = var_33;
    SORT_5 var_34_arg_1 = var_32;
    SORT_5 var_34_arg_2 = var_26;
    SORT_5 var_34 = var_34_arg_0 ? var_34_arg_1 : var_34_arg_2;
    SORT_5 var_39_arg_0 = var_34;
    SORT_38 var_39 = var_39_arg_0 >> 0;
    var_39 = var_39 & mask_SORT_38;
    SORT_5 var_37_arg_0 = var_34;
    SORT_36 var_37 = var_37_arg_0 >> 4;
    var_37 = var_37 & mask_SORT_36;
    SORT_38 var_40_arg_0 = var_39;
    SORT_36 var_40_arg_1 = var_37;
    SORT_5 var_40 = ((SORT_5)var_40_arg_0 << 28) | var_40_arg_1;
    SORT_3 var_42_arg_0 = var_41;
    SORT_5 var_42_arg_1 = var_40;
    SORT_5 var_42_arg_2 = var_34;
    SORT_5 var_42 = var_42_arg_0 ? var_42_arg_1 : var_42_arg_2;
    SORT_5 var_47_arg_0 = var_42;
    SORT_46 var_47 = var_47_arg_0 >> 0;
    var_47 = var_47 & mask_SORT_46;
    SORT_5 var_45_arg_0 = var_42;
    SORT_44 var_45 = var_45_arg_0 >> 8;
    var_45 = var_45 & mask_SORT_44;
    SORT_46 var_48_arg_0 = var_47;
    SORT_44 var_48_arg_1 = var_45;
    SORT_5 var_48 = ((SORT_5)var_48_arg_0 << 24) | var_48_arg_1;
    SORT_3 var_50_arg_0 = var_49;
    SORT_5 var_50_arg_1 = var_48;
    SORT_5 var_50_arg_2 = var_42;
    SORT_5 var_50 = var_50_arg_0 ? var_50_arg_1 : var_50_arg_2;
    SORT_5 var_54_arg_0 = var_50;
    SORT_52 var_54 = var_54_arg_0 >> 0;
    var_54 = var_54 & mask_SORT_52;
    SORT_5 var_53_arg_0 = var_50;
    SORT_52 var_53 = var_53_arg_0 >> 16;
    var_53 = var_53 & mask_SORT_52;
    SORT_52 var_55_arg_0 = var_54;
    SORT_52 var_55_arg_1 = var_53;
    SORT_5 var_55 = ((SORT_5)var_55_arg_0 << 16) | var_55_arg_1;
    SORT_3 var_57_arg_0 = var_56;
    SORT_5 var_57_arg_1 = var_55;
    SORT_5 var_57_arg_2 = var_50;
    SORT_5 var_57 = var_57_arg_0 ? var_57_arg_1 : var_57_arg_2;
    SORT_5 next_59_arg_1 = var_57;
    SORT_5 next_60_arg_1 = input_6;
    // Assigning next states ...
    state_8 = next_59_arg_1;
    state_18 = next_60_arg_1;
  }
}
