// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module lunc.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_3;  // BV with 8 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 8);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (8 - 1);
  typedef unsigned char SORT_46;  // BV with 5 bits
  const SORT_46 mask_SORT_46 = (SORT_46)-1 >> (sizeof(SORT_46) * 8 - 5);
  const SORT_46 msb_SORT_46 = (SORT_46)1 << (5 - 1);
  typedef unsigned char SORT_80;  // BV with 7 bits
  const SORT_80 mask_SORT_80 = (SORT_80)-1 >> (sizeof(SORT_80) * 8 - 7);
  const SORT_80 msb_SORT_80 = (SORT_80)1 << (7 - 1);
  typedef unsigned char SORT_90;  // BV with 2 bits
  const SORT_90 mask_SORT_90 = (SORT_90)-1 >> (sizeof(SORT_90) * 8 - 2);
  const SORT_90 msb_SORT_90 = (SORT_90)1 << (2 - 1);
  typedef unsigned char SORT_92;  // BV with 3 bits
  const SORT_92 mask_SORT_92 = (SORT_92)-1 >> (sizeof(SORT_92) * 8 - 3);
  const SORT_92 msb_SORT_92 = (SORT_92)1 << (3 - 1);
  // Initializing constants ...
  const SORT_3 var_6 = 0;
  const SORT_1 var_11 = 0;
  const SORT_1 var_21 = 1;
  const SORT_46 var_47 = 27;
  const SORT_80 var_81 = 67;
  const SORT_80 var_84 = 85;
  const SORT_80 var_87 = 78;
  const SORT_80 var_96 = 76;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_1 input_5;
  SORT_3 input_56;
  SORT_3 input_59;
  SORT_3 input_61;
  SORT_3 input_63;
  SORT_3 input_65;
  SORT_3 input_67;
  SORT_3 input_69;
  SORT_3 input_72;
  SORT_3 input_74;
  SORT_1 input_79;
  SORT_1 input_103;
  SORT_1 input_112;
  SORT_1 input_121;
  // Collecting state declarations ...
  SORT_3 state_7;
  SORT_1 state_12;
  SORT_1 state_14;
  SORT_1 state_17;
  SORT_1 state_22;
  SORT_3 state_41;
  SORT_3 state_44;
  // Initializing states ...
  SORT_3 init_8_arg_1 = var_6;
  state_7 = init_8_arg_1;
  SORT_1 init_13_arg_1 = var_11;
  state_12 = init_13_arg_1;
  SORT_1 init_15_arg_1 = var_11;
  state_14 = init_15_arg_1;
  SORT_1 init_18_arg_1 = var_11;
  state_17 = init_18_arg_1;
  SORT_1 init_23_arg_1 = var_21;
  state_22 = init_23_arg_1;
  SORT_3 init_42_arg_1 = var_6;
  state_41 = init_42_arg_1;
  SORT_3 init_45_arg_1 = var_6;
  state_44 = init_45_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_char();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_char();
    input_4 = input_4 & mask_SORT_3;
    input_5 = __VERIFIER_nondet_char();
    input_5 = input_5 & mask_SORT_1;
    input_56 = __VERIFIER_nondet_char();
    input_56 = input_56 & mask_SORT_3;
    input_59 = __VERIFIER_nondet_char();
    input_59 = input_59 & mask_SORT_3;
    input_61 = __VERIFIER_nondet_char();
    input_61 = input_61 & mask_SORT_3;
    input_63 = __VERIFIER_nondet_char();
    input_63 = input_63 & mask_SORT_3;
    input_65 = __VERIFIER_nondet_char();
    input_65 = input_65 & mask_SORT_3;
    input_67 = __VERIFIER_nondet_char();
    input_67 = input_67 & mask_SORT_3;
    input_69 = __VERIFIER_nondet_char();
    input_69 = input_69 & mask_SORT_3;
    input_72 = __VERIFIER_nondet_char();
    input_72 = input_72 & mask_SORT_3;
    input_74 = __VERIFIER_nondet_char();
    input_74 = input_74 & mask_SORT_3;
    input_79 = __VERIFIER_nondet_char();
    input_79 = input_79 & mask_SORT_1;
    input_103 = __VERIFIER_nondet_char();
    input_103 = input_103 & mask_SORT_1;
    input_112 = __VERIFIER_nondet_char();
    input_112 = input_112 & mask_SORT_1;
    input_121 = __VERIFIER_nondet_char();
    input_121 = input_121 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_16_arg_0 = state_12;
    SORT_1 var_16_arg_1 = state_14;
    SORT_1 var_16 = var_16_arg_0 & var_16_arg_1;
    var_16 = var_16 & mask_SORT_1;
    SORT_1 var_19_arg_0 = state_12;
    SORT_1 var_19_arg_1 = state_17;
    SORT_1 var_19 = var_19_arg_0 & var_19_arg_1;
    var_19 = var_19 & mask_SORT_1;
    SORT_1 var_20_arg_0 = var_16;
    SORT_1 var_20_arg_1 = var_19;
    SORT_1 var_20 = var_20_arg_0 | var_20_arg_1;
    var_20 = var_20 & mask_SORT_1;
    SORT_1 var_24_arg_0 = state_12;
    SORT_1 var_24_arg_1 = state_22;
    SORT_1 var_24 = var_24_arg_0 & var_24_arg_1;
    var_24 = var_24 & mask_SORT_1;
    SORT_1 var_25_arg_0 = var_20;
    SORT_1 var_25_arg_1 = var_24;
    SORT_1 var_25 = var_25_arg_0 | var_25_arg_1;
    var_25 = var_25 & mask_SORT_1;
    SORT_1 var_26_arg_0 = state_14;
    SORT_1 var_26_arg_1 = state_17;
    SORT_1 var_26 = var_26_arg_0 & var_26_arg_1;
    var_26 = var_26 & mask_SORT_1;
    SORT_1 var_27_arg_0 = var_25;
    SORT_1 var_27_arg_1 = var_26;
    SORT_1 var_27 = var_27_arg_0 | var_27_arg_1;
    var_27 = var_27 & mask_SORT_1;
    SORT_1 var_28_arg_0 = state_14;
    SORT_1 var_28_arg_1 = state_22;
    SORT_1 var_28 = var_28_arg_0 & var_28_arg_1;
    var_28 = var_28 & mask_SORT_1;
    SORT_1 var_29_arg_0 = var_27;
    SORT_1 var_29_arg_1 = var_28;
    SORT_1 var_29 = var_29_arg_0 | var_29_arg_1;
    var_29 = var_29 & mask_SORT_1;
    SORT_1 var_30_arg_0 = state_17;
    SORT_1 var_30_arg_1 = state_22;
    SORT_1 var_30 = var_30_arg_0 & var_30_arg_1;
    var_30 = var_30 & mask_SORT_1;
    SORT_1 var_31_arg_0 = var_29;
    SORT_1 var_31_arg_1 = var_30;
    SORT_1 var_31 = var_31_arg_0 | var_31_arg_1;
    var_31 = var_31 & mask_SORT_1;
    SORT_1 var_32_arg_0 = var_31;
    SORT_1 var_32 = ~var_32_arg_0;
    var_32 = var_32 & mask_SORT_1;
    SORT_1 var_33_arg_0 = var_32;
    SORT_1 var_33 = ~var_33_arg_0;
    var_33 = var_33 & mask_SORT_1;
    SORT_1 var_34_arg_0 = var_21;
    SORT_1 var_34_arg_1 = var_33;
    SORT_1 var_34 = var_34_arg_0 & var_34_arg_1;
    var_34 = var_34 & mask_SORT_1;
    SORT_1 bad_35_arg_0 = var_34;
    __VERIFIER_assert(!(bad_35_arg_0));
    // Computing next states ...
    SORT_1 var_66_arg_0 = state_22;
    SORT_3 var_66_arg_1 = state_41;
    SORT_3 var_66_arg_2 = input_65;
    SORT_3 var_66 = var_66_arg_0 ? var_66_arg_1 : var_66_arg_2;
    SORT_1 var_68_arg_0 = state_14;
    SORT_3 var_68_arg_1 = input_67;
    SORT_3 var_68_arg_2 = var_66;
    SORT_3 var_68 = var_68_arg_0 ? var_68_arg_1 : var_68_arg_2;
    SORT_1 var_70_arg_0 = state_12;
    SORT_3 var_70_arg_1 = input_69;
    SORT_3 var_70_arg_2 = var_68;
    SORT_3 var_70 = var_70_arg_0 ? var_70_arg_1 : var_70_arg_2;
    SORT_1 var_77_arg_0 = input_5;
    SORT_3 var_77_arg_1 = var_6;
    SORT_3 var_77_arg_2 = var_70;
    SORT_3 var_77 = var_77_arg_0 ? var_77_arg_1 : var_77_arg_2;
    SORT_3 next_78_arg_1 = var_77;
    SORT_46 var_48_arg_0 = var_47;
    SORT_3 var_48 = var_48_arg_0;
    SORT_3 var_49_arg_0 = state_44;
    SORT_3 var_49_arg_1 = var_48;
    SORT_1 var_49 = var_49_arg_0 == var_49_arg_1;
    SORT_80 var_97_arg_0 = var_96;
    SORT_3 var_97 = var_97_arg_0;
    SORT_3 var_98_arg_0 = state_41;
    SORT_3 var_98_arg_1 = var_97;
    SORT_1 var_98 = var_98_arg_0 == var_98_arg_1;
    SORT_80 var_88_arg_0 = var_87;
    SORT_3 var_88 = var_88_arg_0;
    SORT_3 var_89_arg_0 = state_41;
    SORT_3 var_89_arg_1 = var_88;
    SORT_1 var_89 = var_89_arg_0 == var_89_arg_1;
    SORT_80 var_85_arg_0 = var_84;
    SORT_3 var_85 = var_85_arg_0;
    SORT_3 var_86_arg_0 = state_41;
    SORT_3 var_86_arg_1 = var_85;
    SORT_1 var_86 = var_86_arg_0 == var_86_arg_1;
    SORT_80 var_82_arg_0 = var_81;
    SORT_3 var_82 = var_82_arg_0;
    SORT_3 var_83_arg_0 = state_41;
    SORT_3 var_83_arg_1 = var_82;
    SORT_1 var_83 = var_83_arg_0 == var_83_arg_1;
    SORT_1 var_91_arg_0 = var_86;
    SORT_1 var_91_arg_1 = var_83;
    SORT_90 var_91 = ((SORT_90)var_91_arg_0 << 1) | var_91_arg_1;
    SORT_1 var_93_arg_0 = var_89;
    SORT_90 var_93_arg_1 = var_91;
    SORT_92 var_93 = ((SORT_92)var_93_arg_0 << 2) | var_93_arg_1;
    SORT_92 var_94_arg_0 = var_93;
    SORT_1 var_94 = var_94_arg_0 != 0;
    SORT_1 var_95_arg_0 = var_94;
    SORT_1 var_95_arg_1 = var_11;
    SORT_1 var_95_arg_2 = input_79;
    SORT_1 var_95 = var_95_arg_0 ? var_95_arg_1 : var_95_arg_2;
    SORT_1 var_99_arg_0 = var_98;
    SORT_1 var_99_arg_1 = var_21;
    SORT_1 var_99_arg_2 = var_95;
    SORT_1 var_99 = var_99_arg_0 ? var_99_arg_1 : var_99_arg_2;
    SORT_1 var_100_arg_0 = var_49;
    SORT_1 var_100_arg_1 = var_99;
    SORT_1 var_100_arg_2 = state_12;
    SORT_1 var_100 = var_100_arg_0 ? var_100_arg_1 : var_100_arg_2;
    SORT_1 var_101_arg_0 = input_5;
    SORT_1 var_101_arg_1 = var_11;
    SORT_1 var_101_arg_2 = var_100;
    SORT_1 var_101 = var_101_arg_0 ? var_101_arg_1 : var_101_arg_2;
    SORT_1 next_102_arg_1 = var_101;
    SORT_1 var_104_arg_0 = var_98;
    SORT_1 var_104_arg_1 = var_83;
    SORT_90 var_104 = ((SORT_90)var_104_arg_0 << 1) | var_104_arg_1;
    SORT_1 var_105_arg_0 = var_89;
    SORT_90 var_105_arg_1 = var_104;
    SORT_92 var_105 = ((SORT_92)var_105_arg_0 << 2) | var_105_arg_1;
    SORT_92 var_106_arg_0 = var_105;
    SORT_1 var_106 = var_106_arg_0 != 0;
    SORT_1 var_107_arg_0 = var_106;
    SORT_1 var_107_arg_1 = var_11;
    SORT_1 var_107_arg_2 = input_103;
    SORT_1 var_107 = var_107_arg_0 ? var_107_arg_1 : var_107_arg_2;
    SORT_1 var_108_arg_0 = var_86;
    SORT_1 var_108_arg_1 = var_21;
    SORT_1 var_108_arg_2 = var_107;
    SORT_1 var_108 = var_108_arg_0 ? var_108_arg_1 : var_108_arg_2;
    SORT_1 var_109_arg_0 = var_49;
    SORT_1 var_109_arg_1 = var_108;
    SORT_1 var_109_arg_2 = state_14;
    SORT_1 var_109 = var_109_arg_0 ? var_109_arg_1 : var_109_arg_2;
    SORT_1 var_110_arg_0 = input_5;
    SORT_1 var_110_arg_1 = var_11;
    SORT_1 var_110_arg_2 = var_109;
    SORT_1 var_110 = var_110_arg_0 ? var_110_arg_1 : var_110_arg_2;
    SORT_1 next_111_arg_1 = var_110;
    SORT_1 var_114_arg_0 = var_86;
    SORT_1 var_114_arg_1 = var_98;
    SORT_90 var_114 = ((SORT_90)var_114_arg_0 << 1) | var_114_arg_1;
    SORT_1 var_115_arg_0 = var_89;
    SORT_90 var_115_arg_1 = var_114;
    SORT_92 var_115 = ((SORT_92)var_115_arg_0 << 2) | var_115_arg_1;
    SORT_92 var_116_arg_0 = var_115;
    SORT_1 var_116 = var_116_arg_0 != 0;
    SORT_1 var_113_arg_0 = var_83;
    SORT_1 var_113_arg_1 = var_21;
    SORT_1 var_113_arg_2 = input_112;
    SORT_1 var_113 = var_113_arg_0 ? var_113_arg_1 : var_113_arg_2;
    SORT_1 var_117_arg_0 = var_116;
    SORT_1 var_117_arg_1 = var_11;
    SORT_1 var_117_arg_2 = var_113;
    SORT_1 var_117 = var_117_arg_0 ? var_117_arg_1 : var_117_arg_2;
    SORT_1 var_118_arg_0 = var_49;
    SORT_1 var_118_arg_1 = var_117;
    SORT_1 var_118_arg_2 = state_17;
    SORT_1 var_118 = var_118_arg_0 ? var_118_arg_1 : var_118_arg_2;
    SORT_1 var_119_arg_0 = input_5;
    SORT_1 var_119_arg_1 = var_11;
    SORT_1 var_119_arg_2 = var_118;
    SORT_1 var_119 = var_119_arg_0 ? var_119_arg_1 : var_119_arg_2;
    SORT_1 next_120_arg_1 = var_119;
    SORT_1 var_122_arg_0 = var_98;
    SORT_1 var_122_arg_1 = var_83;
    SORT_90 var_122 = ((SORT_90)var_122_arg_0 << 1) | var_122_arg_1;
    SORT_1 var_123_arg_0 = var_86;
    SORT_90 var_123_arg_1 = var_122;
    SORT_92 var_123 = ((SORT_92)var_123_arg_0 << 2) | var_123_arg_1;
    SORT_92 var_124_arg_0 = var_123;
    SORT_1 var_124 = var_124_arg_0 != 0;
    SORT_1 var_125_arg_0 = var_124;
    SORT_1 var_125_arg_1 = var_11;
    SORT_1 var_125_arg_2 = input_121;
    SORT_1 var_125 = var_125_arg_0 ? var_125_arg_1 : var_125_arg_2;
    SORT_1 var_126_arg_0 = var_89;
    SORT_1 var_126_arg_1 = var_21;
    SORT_1 var_126_arg_2 = var_125;
    SORT_1 var_126 = var_126_arg_0 ? var_126_arg_1 : var_126_arg_2;
    SORT_1 var_127_arg_0 = var_49;
    SORT_1 var_127_arg_1 = var_126;
    SORT_1 var_127_arg_2 = state_22;
    SORT_1 var_127 = var_127_arg_0 ? var_127_arg_1 : var_127_arg_2;
    SORT_1 var_128_arg_0 = input_5;
    SORT_1 var_128_arg_1 = var_21;
    SORT_1 var_128_arg_2 = var_127;
    SORT_1 var_128 = var_128_arg_0 ? var_128_arg_1 : var_128_arg_2;
    SORT_1 next_129_arg_1 = var_128;
    SORT_1 var_130_arg_0 = input_5;
    SORT_3 var_130_arg_1 = var_6;
    SORT_3 var_130_arg_2 = input_4;
    SORT_3 var_130 = var_130_arg_0 ? var_130_arg_1 : var_130_arg_2;
    SORT_3 next_131_arg_1 = var_130;
    SORT_1 var_132_arg_0 = input_5;
    SORT_3 var_132_arg_1 = var_6;
    SORT_3 var_132_arg_2 = state_41;
    SORT_3 var_132 = var_132_arg_0 ? var_132_arg_1 : var_132_arg_2;
    SORT_3 next_133_arg_1 = var_132;
    // Assigning next states ...
    state_7 = next_78_arg_1;
    state_12 = next_102_arg_1;
    state_14 = next_111_arg_1;
    state_17 = next_120_arg_1;
    state_22 = next_129_arg_1;
    state_41 = next_131_arg_1;
    state_44 = next_133_arg_1;
  }
}
