// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module fru.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned int SORT_1;  // BV with 6 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 6);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (6 - 1);
  typedef unsigned int SORT_3;  // BV with 1 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 1);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (1 - 1);
  typedef unsigned int SORT_6;  // BV with 32 bits
  const SORT_6 mask_SORT_6 = (SORT_6)-1 >> (sizeof(SORT_6) * 8 - 32);
  const SORT_6 msb_SORT_6 = (SORT_6)1 << (32 - 1);
  typedef unsigned int SORT_39;  // BV with 5 bits
  const SORT_39 mask_SORT_39 = (SORT_39)-1 >> (sizeof(SORT_39) * 8 - 5);
  const SORT_39 msb_SORT_39 = (SORT_39)1 << (5 - 1);
  typedef unsigned int SORT_45;  // BV with 2 bits
  const SORT_45 mask_SORT_45 = (SORT_45)-1 >> (sizeof(SORT_45) * 8 - 2);
  const SORT_45 msb_SORT_45 = (SORT_45)1 << (2 - 1);
  typedef unsigned int SORT_154;  // BV with 4 bits
  const SORT_154 mask_SORT_154 = (SORT_154)-1 >> (sizeof(SORT_154) * 8 - 4);
  const SORT_154 msb_SORT_154 = (SORT_154)1 << (4 - 1);
  // Initializing constants ...
  const SORT_6 var_22 = 0;
  const SORT_3 var_23 = 0;
  const SORT_3 var_24 = 1;
  const SORT_1 var_25 = 0;
  const SORT_39 var_41 = 31;
  const SORT_45 var_47 = 2;
  const SORT_45 var_60 = 3;
  const SORT_154 var_155 = 0;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_1 input_5;
  SORT_6 input_7;
  SORT_3 input_8;
  SORT_6 input_9;
  SORT_1 input_10;
  SORT_1 input_11;
  SORT_1 input_12;
  SORT_3 input_13;
  SORT_3 input_14;
  SORT_3 input_15;
  SORT_3 input_16;
  SORT_3 input_17;
  SORT_3 input_18;
  SORT_3 input_19;
  SORT_3 input_20;
  SORT_6 input_21;
  SORT_6 input_96;
  // Collecting state declarations ...
  SORT_1 state_26;
  SORT_1 state_29;
  SORT_3 state_33;
  SORT_3 state_36;
  SORT_1 state_48;
  SORT_3 state_52;
  SORT_3 state_55;
  SORT_1 state_61;
  SORT_3 state_65;
  SORT_3 state_69;
  SORT_3 state_72;
  SORT_6 state_80;
  SORT_6 state_85;
  SORT_6 state_89;
  SORT_1 state_97;
  SORT_1 state_152;
  SORT_3 state_158;
  SORT_3 state_160;
  // Initializing states ...
  SORT_1 init_27_arg_1 = var_25;
  state_26 = init_27_arg_1;
  SORT_1 init_30_arg_1 = var_25;
  state_29 = init_30_arg_1;
  SORT_3 init_34_arg_1 = var_23;
  state_33 = init_34_arg_1;
  SORT_3 init_37_arg_1 = var_23;
  state_36 = init_37_arg_1;
  SORT_1 init_49_arg_1 = var_25;
  state_48 = init_49_arg_1;
  SORT_3 init_53_arg_1 = var_23;
  state_52 = init_53_arg_1;
  SORT_3 init_56_arg_1 = var_23;
  state_55 = init_56_arg_1;
  SORT_1 init_62_arg_1 = var_25;
  state_61 = init_62_arg_1;
  SORT_3 init_66_arg_1 = var_23;
  state_65 = init_66_arg_1;
  SORT_3 init_70_arg_1 = var_23;
  state_69 = init_70_arg_1;
  SORT_3 init_73_arg_1 = var_23;
  state_72 = init_73_arg_1;
  SORT_6 init_81_arg_1 = var_22;
  state_80 = init_81_arg_1;
  SORT_6 init_86_arg_1 = var_22;
  state_85 = init_86_arg_1;
  SORT_6 init_90_arg_1 = var_22;
  state_89 = init_90_arg_1;
  SORT_1 init_98_arg_1 = var_25;
  state_97 = init_98_arg_1;
  SORT_1 init_153_arg_1 = var_25;
  state_152 = init_153_arg_1;
  SORT_3 init_159_arg_1 = var_23;
  state_158 = init_159_arg_1;
  SORT_3 init_161_arg_1 = var_23;
  state_160 = init_161_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_int();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_int();
    input_4 = input_4 & mask_SORT_3;
    input_5 = __VERIFIER_nondet_int();
    input_5 = input_5 & mask_SORT_1;
    input_7 = __VERIFIER_nondet_int();
    input_7 = input_7 & mask_SORT_6;
    input_8 = __VERIFIER_nondet_int();
    input_8 = input_8 & mask_SORT_3;
    input_9 = __VERIFIER_nondet_int();
    input_9 = input_9 & mask_SORT_6;
    input_10 = __VERIFIER_nondet_int();
    input_10 = input_10 & mask_SORT_1;
    input_11 = __VERIFIER_nondet_int();
    input_11 = input_11 & mask_SORT_1;
    input_12 = __VERIFIER_nondet_int();
    input_12 = input_12 & mask_SORT_1;
    input_13 = __VERIFIER_nondet_int();
    input_13 = input_13 & mask_SORT_3;
    input_14 = __VERIFIER_nondet_int();
    input_14 = input_14 & mask_SORT_3;
    input_15 = __VERIFIER_nondet_int();
    input_15 = input_15 & mask_SORT_3;
    input_16 = __VERIFIER_nondet_int();
    input_16 = input_16 & mask_SORT_3;
    input_17 = __VERIFIER_nondet_int();
    input_17 = input_17 & mask_SORT_3;
    input_18 = __VERIFIER_nondet_int();
    input_18 = input_18 & mask_SORT_3;
    input_19 = __VERIFIER_nondet_int();
    input_19 = input_19 & mask_SORT_3;
    input_20 = __VERIFIER_nondet_int();
    input_20 = input_20 & mask_SORT_3;
    input_21 = __VERIFIER_nondet_int();
    input_21 = input_21 & mask_SORT_6;
    input_96 = __VERIFIER_nondet_int();
    input_96 = input_96 & mask_SORT_6;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_40_arg_0 = state_26;
    SORT_39 var_40 = var_40_arg_0 >> 0;
    var_40 = var_40 & mask_SORT_39;
    SORT_39 var_93_arg_0 = var_40;
    SORT_39 var_93_arg_1 = var_41;
    SORT_3 var_93 = var_93_arg_0 == var_93_arg_1;
    SORT_1 var_28_arg_0 = state_26;
    SORT_3 var_28 = var_28_arg_0 >> 5;
    var_28 = var_28 & mask_SORT_3;
    SORT_1 var_63_arg_0 = state_26;
    SORT_1 var_63_arg_1 = state_61;
    SORT_3 var_63 = var_63_arg_0 == var_63_arg_1;
    SORT_3 var_64_arg_0 = var_28;
    SORT_3 var_64_arg_1 = var_63;
    SORT_3 var_64 = var_64_arg_0 & var_64_arg_1;
    var_64 = var_64 & mask_SORT_3;
    SORT_3 var_67_arg_0 = state_65;
    SORT_3 var_67 = ~var_67_arg_0;
    var_67 = var_67 & mask_SORT_3;
    SORT_3 var_68_arg_0 = var_64;
    SORT_3 var_68_arg_1 = var_67;
    SORT_3 var_68 = var_68_arg_0 & var_68_arg_1;
    var_68 = var_68 & mask_SORT_3;
    SORT_3 var_71_arg_0 = var_68;
    SORT_3 var_71_arg_1 = state_69;
    SORT_3 var_71 = var_71_arg_0 & var_71_arg_1;
    var_71 = var_71 & mask_SORT_3;
    SORT_3 var_74_arg_0 = var_71;
    SORT_3 var_74_arg_1 = state_72;
    SORT_3 var_74 = var_74_arg_0 & var_74_arg_1;
    var_74 = var_74 & mask_SORT_3;
    SORT_39 var_42_arg_0 = var_40;
    SORT_39 var_42_arg_1 = var_41;
    SORT_3 var_42 = var_42_arg_0 != var_42_arg_1;
    SORT_3 var_75_arg_0 = var_74;
    SORT_3 var_75_arg_1 = var_42;
    SORT_3 var_75 = var_75_arg_0 & var_75_arg_1;
    var_75 = var_75 & mask_SORT_3;
    SORT_1 var_50_arg_0 = state_26;
    SORT_1 var_50_arg_1 = state_48;
    SORT_3 var_50 = var_50_arg_0 == var_50_arg_1;
    SORT_3 var_51_arg_0 = var_28;
    SORT_3 var_51_arg_1 = var_50;
    SORT_3 var_51 = var_51_arg_0 & var_51_arg_1;
    var_51 = var_51 & mask_SORT_3;
    SORT_3 var_54_arg_0 = var_51;
    SORT_3 var_54_arg_1 = state_52;
    SORT_3 var_54 = var_54_arg_0 & var_54_arg_1;
    var_54 = var_54 & mask_SORT_3;
    SORT_3 var_57_arg_0 = var_54;
    SORT_3 var_57_arg_1 = state_55;
    SORT_3 var_57 = var_57_arg_0 & var_57_arg_1;
    var_57 = var_57 & mask_SORT_3;
    SORT_3 var_58_arg_0 = var_57;
    SORT_3 var_58_arg_1 = var_42;
    SORT_3 var_58 = var_58_arg_0 & var_58_arg_1;
    var_58 = var_58 & mask_SORT_3;
    SORT_1 var_31_arg_0 = state_26;
    SORT_1 var_31_arg_1 = state_29;
    SORT_3 var_31 = var_31_arg_0 == var_31_arg_1;
    SORT_3 var_32_arg_0 = var_28;
    SORT_3 var_32_arg_1 = var_31;
    SORT_3 var_32 = var_32_arg_0 & var_32_arg_1;
    var_32 = var_32 & mask_SORT_3;
    SORT_3 var_35_arg_0 = var_32;
    SORT_3 var_35_arg_1 = state_33;
    SORT_3 var_35 = var_35_arg_0 & var_35_arg_1;
    var_35 = var_35 & mask_SORT_3;
    SORT_3 var_38_arg_0 = var_35;
    SORT_3 var_38_arg_1 = state_36;
    SORT_3 var_38 = var_38_arg_0 & var_38_arg_1;
    var_38 = var_38 & mask_SORT_3;
    SORT_3 var_43_arg_0 = var_38;
    SORT_3 var_43_arg_1 = var_42;
    SORT_3 var_43 = var_43_arg_0 & var_43_arg_1;
    var_43 = var_43 & mask_SORT_3;
    SORT_3 var_44_arg_0 = var_43;
    SORT_3 var_44_arg_1 = var_24;
    SORT_3 var_44_arg_2 = var_23;
    SORT_3 var_44 = var_44_arg_0 ? var_44_arg_1 : var_44_arg_2;
    SORT_3 var_46_arg_0 = var_23;
    SORT_3 var_46_arg_1 = var_44;
    SORT_45 var_46 = ((SORT_45)var_46_arg_0 << 1) | var_46_arg_1;
    SORT_3 var_59_arg_0 = var_58;
    SORT_45 var_59_arg_1 = var_47;
    SORT_45 var_59_arg_2 = var_46;
    SORT_45 var_59 = var_59_arg_0 ? var_59_arg_1 : var_59_arg_2;
    SORT_3 var_76_arg_0 = var_75;
    SORT_45 var_76_arg_1 = var_60;
    SORT_45 var_76_arg_2 = var_59;
    SORT_45 var_76 = var_76_arg_0 ? var_76_arg_1 : var_76_arg_2;
    SORT_45 var_91_arg_0 = var_76;
    SORT_45 var_91_arg_1 = var_60;
    SORT_3 var_91 = var_91_arg_0 == var_91_arg_1;
    SORT_45 var_87_arg_0 = var_76;
    SORT_45 var_87_arg_1 = var_47;
    SORT_3 var_87 = var_87_arg_0 == var_87_arg_1;
    SORT_3 var_82_arg_0 = var_24;
    SORT_45 var_82 = var_82_arg_0;
    SORT_45 var_83_arg_0 = var_76;
    SORT_45 var_83_arg_1 = var_82;
    SORT_3 var_83 = var_83_arg_0 == var_83_arg_1;
    SORT_45 var_77_arg_0 = var_76;
    SORT_3 var_77 = var_77_arg_0 != 0;
    SORT_3 var_78_arg_0 = var_77;
    SORT_3 var_78 = ~var_78_arg_0;
    var_78 = var_78 & mask_SORT_3;
    SORT_3 var_79_arg_0 = var_78;
    SORT_6 var_79_arg_1 = var_22;
    SORT_6 var_79_arg_2 = input_21;
    SORT_6 var_79 = var_79_arg_0 ? var_79_arg_1 : var_79_arg_2;
    SORT_3 var_84_arg_0 = var_83;
    SORT_6 var_84_arg_1 = state_80;
    SORT_6 var_84_arg_2 = var_79;
    SORT_6 var_84 = var_84_arg_0 ? var_84_arg_1 : var_84_arg_2;
    SORT_3 var_88_arg_0 = var_87;
    SORT_6 var_88_arg_1 = state_85;
    SORT_6 var_88_arg_2 = var_84;
    SORT_6 var_88 = var_88_arg_0 ? var_88_arg_1 : var_88_arg_2;
    SORT_3 var_92_arg_0 = var_91;
    SORT_6 var_92_arg_1 = state_89;
    SORT_6 var_92_arg_2 = var_88;
    SORT_6 var_92 = var_92_arg_0 ? var_92_arg_1 : var_92_arg_2;
    SORT_3 var_94_arg_0 = var_93;
    SORT_6 var_94_arg_1 = var_22;
    SORT_6 var_94_arg_2 = var_92;
    SORT_6 var_94 = var_94_arg_0 ? var_94_arg_1 : var_94_arg_2;
    SORT_6 var_144_arg_0 = var_94;
    SORT_1 var_144 = var_144_arg_0 >> 26;
    var_144 = var_144 & mask_SORT_1;
    SORT_1 var_145_arg_0 = var_144;
    SORT_3 var_145 = var_145_arg_0 != 0;
    SORT_3 var_146_arg_0 = var_145;
    SORT_3 var_146 = ~var_146_arg_0;
    var_146 = var_146 & mask_SORT_3;
    SORT_3 var_147_arg_0 = var_93;
    SORT_3 var_147_arg_1 = var_146;
    SORT_3 var_147 = var_147_arg_0 & var_147_arg_1;
    var_147 = var_147 & mask_SORT_3;
    SORT_3 var_148_arg_0 = var_147;
    SORT_3 var_148 = ~var_148_arg_0;
    var_148 = var_148 & mask_SORT_3;
    SORT_3 var_149_arg_0 = var_148;
    SORT_3 var_149 = ~var_149_arg_0;
    var_149 = var_149 & mask_SORT_3;
    SORT_3 var_150_arg_0 = var_24;
    SORT_3 var_150_arg_1 = var_149;
    SORT_3 var_150 = var_150_arg_0 & var_150_arg_1;
    var_150 = var_150 & mask_SORT_3;
    SORT_3 bad_151_arg_0 = var_150;
    __VERIFIER_assert(!(bad_151_arg_0));
    // Computing next states ...
    SORT_1 next_172_arg_1 = input_11;
    SORT_3 var_173_arg_0 = state_160;
    SORT_1 var_173_arg_1 = state_48;
    SORT_1 var_173_arg_2 = state_29;
    SORT_1 var_173 = var_173_arg_0 ? var_173_arg_1 : var_173_arg_2;
    SORT_1 next_174_arg_1 = var_173;
    SORT_3 next_175_arg_1 = input_19;
    SORT_3 var_176_arg_0 = state_160;
    SORT_3 var_176_arg_1 = state_52;
    SORT_3 var_176_arg_2 = state_36;
    SORT_3 var_176 = var_176_arg_0 ? var_176_arg_1 : var_176_arg_2;
    SORT_3 next_177_arg_1 = var_176;
    SORT_1 next_178_arg_1 = input_10;
    SORT_3 next_179_arg_1 = input_8;
    SORT_3 next_180_arg_1 = input_18;
    SORT_1 next_181_arg_1 = input_5;
    SORT_1 var_182_arg_0 = state_152;
    SORT_3 var_182 = var_182_arg_0 >> 5;
    var_182 = var_182 & mask_SORT_3;
    SORT_1 var_183_arg_0 = state_152;
    SORT_3 var_183 = var_183_arg_0 >> 2;
    var_183 = var_183 & mask_SORT_3;
    SORT_3 var_184_arg_0 = var_182;
    SORT_3 var_184_arg_1 = var_183;
    SORT_3 var_184 = var_184_arg_0 & var_184_arg_1;
    var_184 = var_184 & mask_SORT_3;
    SORT_1 var_185_arg_0 = state_152;
    SORT_3 var_185 = var_185_arg_0 >> 0;
    var_185 = var_185 & mask_SORT_3;
    SORT_3 var_186_arg_0 = var_185;
    SORT_3 var_186 = ~var_186_arg_0;
    var_186 = var_186 & mask_SORT_3;
    SORT_3 var_187_arg_0 = var_184;
    SORT_3 var_187_arg_1 = var_186;
    SORT_3 var_187 = var_187_arg_0 & var_187_arg_1;
    var_187 = var_187 & mask_SORT_3;
    SORT_3 var_188_arg_0 = state_158;
    SORT_3 var_188_arg_1 = var_187;
    SORT_3 var_188_arg_2 = state_65;
    SORT_3 var_188 = var_188_arg_0 ? var_188_arg_1 : var_188_arg_2;
    SORT_3 next_189_arg_1 = var_188;
    SORT_3 next_190_arg_1 = input_4;
    SORT_3 next_191_arg_1 = input_17;
    SORT_3 var_192_arg_0 = state_160;
    SORT_6 var_192_arg_1 = state_85;
    SORT_6 var_192_arg_2 = state_80;
    SORT_6 var_192 = var_192_arg_0 ? var_192_arg_1 : var_192_arg_2;
    SORT_6 next_193_arg_1 = var_192;
    SORT_6 next_194_arg_1 = input_9;
    SORT_6 next_195_arg_1 = input_7;
    SORT_1 next_196_arg_1 = input_12;
    SORT_1 next_197_arg_1 = input_2;
    SORT_3 next_198_arg_1 = input_14;
    SORT_3 next_199_arg_1 = input_16;
    // Assigning next states ...
    state_26 = next_172_arg_1;
    state_29 = next_174_arg_1;
    state_33 = next_175_arg_1;
    state_36 = next_177_arg_1;
    state_48 = next_178_arg_1;
    state_52 = next_179_arg_1;
    state_55 = next_180_arg_1;
    state_61 = next_181_arg_1;
    state_65 = next_189_arg_1;
    state_69 = next_190_arg_1;
    state_72 = next_191_arg_1;
    state_80 = next_193_arg_1;
    state_85 = next_194_arg_1;
    state_89 = next_195_arg_1;
    state_97 = next_196_arg_1;
    state_152 = next_197_arg_1;
    state_158 = next_198_arg_1;
    state_160 = next_199_arg_1;
  }
}
