// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module palu.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned int SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned int SORT_3;  // BV with 2 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 2);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (2 - 1);
  typedef unsigned int SORT_5;  // BV with 3 bits
  const SORT_5 mask_SORT_5 = (SORT_5)-1 >> (sizeof(SORT_5) * 8 - 3);
  const SORT_5 msb_SORT_5 = (SORT_5)1 << (3 - 1);
  typedef unsigned int SORT_10;  // BV with 4 bits
  const SORT_10 mask_SORT_10 = (SORT_10)-1 >> (sizeof(SORT_10) * 8 - 4);
  const SORT_10 msb_SORT_10 = (SORT_10)1 << (4 - 1);
  typedef unsigned int SORT_52;  // BV with 32 bits
  const SORT_52 mask_SORT_52 = (SORT_52)-1 >> (sizeof(SORT_52) * 8 - 32);
  const SORT_52 msb_SORT_52 = (SORT_52)1 << (32 - 1);
  // Initializing constants ...
  const SORT_10 var_11 = 0;
  const SORT_1 var_15 = 0;
  const SORT_10 var_23 = 9;
  const SORT_1 var_35 = 1;
  const SORT_3 var_47 = 0;
  const SORT_52 var_53 = 4;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_5 input_6;
  SORT_3 input_7;
  SORT_3 input_8;
  SORT_1 input_9;
  SORT_10 input_59;
  SORT_3 input_61;
  SORT_10 input_86;
  // Collecting state declarations ...
  SORT_10 state_12;
  SORT_1 state_16;
  SORT_1 state_18;
  SORT_10 state_21;
  SORT_10 state_25;
  SORT_10 state_29;
  SORT_10 state_32;
  SORT_10 state_46;
  SORT_3 state_48;
  SORT_3 state_50;
  // Initializing states ...
  SORT_10 init_13_arg_1 = var_11;
  state_12 = init_13_arg_1;
  SORT_1 init_17_arg_1 = var_15;
  state_16 = init_17_arg_1;
  SORT_1 init_19_arg_1 = var_15;
  state_18 = init_19_arg_1;
  SORT_10 init_22_arg_1 = var_11;
  state_21 = init_22_arg_1;
  SORT_10 init_26_arg_1 = var_11;
  state_25 = init_26_arg_1;
  SORT_10 init_30_arg_1 = var_11;
  state_29 = init_30_arg_1;
  SORT_10 init_33_arg_1 = var_11;
  state_32 = init_33_arg_1;
  SORT_3 init_49_arg_1 = var_47;
  state_48 = init_49_arg_1;
  SORT_3 init_51_arg_1 = var_47;
  state_50 = init_51_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_int();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_int();
    input_4 = input_4 & mask_SORT_3;
    input_6 = __VERIFIER_nondet_int();
    input_6 = input_6 & mask_SORT_5;
    input_7 = __VERIFIER_nondet_int();
    input_7 = input_7 & mask_SORT_3;
    input_8 = __VERIFIER_nondet_int();
    input_8 = input_8 & mask_SORT_3;
    input_9 = __VERIFIER_nondet_int();
    input_9 = input_9 & mask_SORT_1;
    input_59 = __VERIFIER_nondet_int();
    input_59 = input_59 & mask_SORT_10;
    input_61 = __VERIFIER_nondet_int();
    input_61 = input_61 & mask_SORT_3;
    input_86 = __VERIFIER_nondet_int();
    input_86 = input_86 & mask_SORT_10;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_20_arg_0 = state_16;
    SORT_1 var_20_arg_1 = state_18;
    SORT_1 var_20 = var_20_arg_0 & var_20_arg_1;
    var_20 = var_20 & mask_SORT_1;
    SORT_10 var_24_arg_0 = state_21;
    SORT_10 var_24_arg_1 = var_23;
    SORT_1 var_24 = var_24_arg_0 == var_24_arg_1;
    SORT_10 var_27_arg_0 = state_25;
    SORT_10 var_27_arg_1 = var_23;
    SORT_1 var_27 = var_27_arg_0 == var_27_arg_1;
    SORT_1 var_28_arg_0 = var_24;
    SORT_1 var_28_arg_1 = var_27;
    SORT_1 var_28 = var_28_arg_0 | var_28_arg_1;
    var_28 = var_28 & mask_SORT_1;
    SORT_1 var_34_arg_0 = var_15;
    SORT_10 var_34_arg_1 = state_21;
    SORT_10 var_34_arg_2 = state_32;
    SORT_10 var_34 = var_34_arg_0 ? var_34_arg_1 : var_34_arg_2;
    SORT_1 var_31_arg_0 = var_15;
    SORT_10 var_31_arg_1 = state_25;
    SORT_10 var_31_arg_2 = state_29;
    SORT_10 var_31 = var_31_arg_0 ? var_31_arg_1 : var_31_arg_2;
    SORT_1 var_36_arg_0 = var_35;
    SORT_10 var_36_arg_1 = var_34;
    SORT_10 var_36_arg_2 = var_31;
    SORT_10 var_36 = var_36_arg_0 ? var_36_arg_1 : var_36_arg_2;
    SORT_10 var_37_arg_0 = var_36;
    SORT_10 var_37_arg_1 = var_23;
    SORT_1 var_37 = var_37_arg_0 == var_37_arg_1;
    SORT_1 var_38_arg_0 = var_28;
    SORT_1 var_38_arg_1 = var_37;
    SORT_1 var_38 = var_38_arg_0 | var_38_arg_1;
    var_38 = var_38 & mask_SORT_1;
    SORT_10 var_39_arg_0 = state_29;
    SORT_10 var_39_arg_1 = var_23;
    SORT_1 var_39 = var_39_arg_0 == var_39_arg_1;
    SORT_1 var_40_arg_0 = var_38;
    SORT_1 var_40_arg_1 = var_39;
    SORT_1 var_40 = var_40_arg_0 | var_40_arg_1;
    var_40 = var_40 & mask_SORT_1;
    SORT_1 var_41_arg_0 = var_20;
    SORT_1 var_41_arg_1 = var_40;
    SORT_1 var_41 = var_41_arg_0 & var_41_arg_1;
    var_41 = var_41 & mask_SORT_1;
    SORT_1 var_42_arg_0 = var_41;
    SORT_1 var_42 = ~var_42_arg_0;
    var_42 = var_42 & mask_SORT_1;
    SORT_1 var_43_arg_0 = var_42;
    SORT_1 var_43 = ~var_43_arg_0;
    var_43 = var_43 & mask_SORT_1;
    SORT_1 var_44_arg_0 = var_35;
    SORT_1 var_44_arg_1 = var_43;
    SORT_1 var_44 = var_44_arg_0 & var_44_arg_1;
    var_44 = var_44 & mask_SORT_1;
    SORT_1 bad_45_arg_0 = var_44;
    __VERIFIER_assert(!(bad_45_arg_0));
    // Computing next states ...
    SORT_1 var_55_arg_0 = state_16;
    SORT_10 var_55_arg_1 = state_12;
    SORT_10 var_55_arg_2 = state_46;
    SORT_10 var_55 = var_55_arg_0 ? var_55_arg_1 : var_55_arg_2;
    SORT_10 next_56_arg_1 = var_55;
    SORT_1 next_57_arg_1 = input_9;
    SORT_1 next_58_arg_1 = state_16;
    SORT_1 var_62_arg_0 = state_18;
    SORT_3 var_62_arg_1 = input_61;
    SORT_3 var_62_arg_2 = state_50;
    SORT_3 var_62 = var_62_arg_0 ? var_62_arg_1 : var_62_arg_2;
    SORT_3 var_63_arg_0 = var_62;
    SORT_1 var_63 = var_63_arg_0 >> 0;
    var_63 = var_63 & mask_SORT_1;
    SORT_1 var_64_arg_0 = var_63;
    SORT_1 var_64_arg_1 = var_35;
    SORT_1 var_64 = var_64_arg_0 == var_64_arg_1;
    SORT_3 var_65_arg_0 = var_62;
    SORT_1 var_65 = var_65_arg_0 >> 1;
    var_65 = var_65 & mask_SORT_1;
    SORT_1 var_66_arg_0 = var_65;
    SORT_1 var_66_arg_1 = var_35;
    SORT_1 var_66 = var_66_arg_0 == var_66_arg_1;
    SORT_1 var_67_arg_0 = var_64;
    SORT_1 var_67_arg_1 = var_66;
    SORT_1 var_67 = var_67_arg_0 & var_67_arg_1;
    var_67 = var_67 & mask_SORT_1;
    SORT_1 var_68_arg_0 = state_18;
    SORT_1 var_68_arg_1 = var_15;
    SORT_1 var_68_arg_2 = var_35;
    SORT_1 var_68 = var_68_arg_0 ? var_68_arg_1 : var_68_arg_2;
    SORT_1 var_69_arg_0 = var_67;
    SORT_1 var_69_arg_1 = var_68;
    SORT_1 var_69 = var_69_arg_0 & var_69_arg_1;
    var_69 = var_69 & mask_SORT_1;
    SORT_1 var_60_arg_0 = state_18;
    SORT_10 var_60_arg_1 = input_59;
    SORT_10 var_60_arg_2 = state_12;
    SORT_10 var_60 = var_60_arg_0 ? var_60_arg_1 : var_60_arg_2;
    SORT_1 var_70_arg_0 = var_69;
    SORT_10 var_70_arg_1 = var_60;
    SORT_10 var_70_arg_2 = state_21;
    SORT_10 var_70 = var_70_arg_0 ? var_70_arg_1 : var_70_arg_2;
    SORT_10 next_71_arg_1 = var_70;
    SORT_1 var_72_arg_0 = var_65;
    SORT_1 var_72_arg_1 = var_15;
    SORT_1 var_72 = var_72_arg_0 == var_72_arg_1;
    SORT_1 var_73_arg_0 = var_64;
    SORT_1 var_73_arg_1 = var_72;
    SORT_1 var_73 = var_73_arg_0 & var_73_arg_1;
    var_73 = var_73 & mask_SORT_1;
    SORT_1 var_74_arg_0 = var_73;
    SORT_1 var_74_arg_1 = var_68;
    SORT_1 var_74 = var_74_arg_0 & var_74_arg_1;
    var_74 = var_74 & mask_SORT_1;
    SORT_1 var_75_arg_0 = var_74;
    SORT_10 var_75_arg_1 = var_60;
    SORT_10 var_75_arg_2 = state_25;
    SORT_10 var_75 = var_75_arg_0 ? var_75_arg_1 : var_75_arg_2;
    SORT_10 next_76_arg_1 = var_75;
    SORT_1 var_77_arg_0 = var_63;
    SORT_1 var_77_arg_1 = var_15;
    SORT_1 var_77 = var_77_arg_0 == var_77_arg_1;
    SORT_1 var_78_arg_0 = var_77;
    SORT_1 var_78_arg_1 = var_72;
    SORT_1 var_78 = var_78_arg_0 & var_78_arg_1;
    var_78 = var_78 & mask_SORT_1;
    SORT_1 var_79_arg_0 = var_78;
    SORT_1 var_79_arg_1 = var_68;
    SORT_1 var_79 = var_79_arg_0 & var_79_arg_1;
    var_79 = var_79 & mask_SORT_1;
    SORT_1 var_80_arg_0 = var_79;
    SORT_10 var_80_arg_1 = var_60;
    SORT_10 var_80_arg_2 = state_29;
    SORT_10 var_80 = var_80_arg_0 ? var_80_arg_1 : var_80_arg_2;
    SORT_10 next_81_arg_1 = var_80;
    SORT_1 var_82_arg_0 = var_77;
    SORT_1 var_82_arg_1 = var_66;
    SORT_1 var_82 = var_82_arg_0 & var_82_arg_1;
    var_82 = var_82 & mask_SORT_1;
    SORT_1 var_83_arg_0 = var_82;
    SORT_1 var_83_arg_1 = var_68;
    SORT_1 var_83 = var_83_arg_0 & var_83_arg_1;
    var_83 = var_83 & mask_SORT_1;
    SORT_1 var_84_arg_0 = var_83;
    SORT_10 var_84_arg_1 = var_60;
    SORT_10 var_84_arg_2 = state_32;
    SORT_10 var_84 = var_84_arg_0 ? var_84_arg_1 : var_84_arg_2;
    SORT_10 next_85_arg_1 = var_84;
    SORT_10 next_87_arg_1 = input_86;
    SORT_1 var_88_arg_0 = input_9;
    SORT_3 var_88_arg_1 = state_48;
    SORT_3 var_88_arg_2 = input_4;
    SORT_3 var_88 = var_88_arg_0 ? var_88_arg_1 : var_88_arg_2;
    SORT_3 next_89_arg_1 = var_88;
    SORT_1 var_90_arg_0 = state_16;
    SORT_3 var_90_arg_1 = state_50;
    SORT_3 var_90_arg_2 = state_48;
    SORT_3 var_90 = var_90_arg_0 ? var_90_arg_1 : var_90_arg_2;
    SORT_3 next_91_arg_1 = var_90;
    // Assigning next states ...
    state_12 = next_56_arg_1;
    state_16 = next_57_arg_1;
    state_18 = next_58_arg_1;
    state_21 = next_71_arg_1;
    state_25 = next_76_arg_1;
    state_29 = next_81_arg_1;
    state_32 = next_85_arg_1;
    state_46 = next_87_arg_1;
    state_48 = next_89_arg_1;
    state_50 = next_91_arg_1;
  }
}
