// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2016 Ahmed Irfan
// SPDX-FileCopyrightText: 2016 Alberto Griggio
// SPDX-FileCopyrightText: 2016 Alessandro Cimatti
// SPDX-FileCopyrightText: 2016 Marco Roveri
// SPDX-FileCopyrightText: 2016 Roberto Sebastiani
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from BTOR2 by BTOR2C version 3a07601
//   with arguments: { architecture=32, lazy_modulo=false, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=false, decimal_constant=true }
// Comments from the original BTOR2 file:
// ; source: https://es-static.fbk.eu/tools/verilog2smv/dload/verilog2smv-1.1.3.tar.gz
// ; BTOR description generated by Yosys 0.21+7 (git sha1 d98738db5, clang 14.0.0-1ubuntu1 -fPIC -Os) for module spinner.
extern void abort(void);
void reach_error() {}
extern char __VERIFIER_nondet_char();
extern short __VERIFIER_nondet_short();
extern int __VERIFIER_nondet_int();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
void main() {
  // Defining sorts ...
  typedef unsigned int SORT_1;  // BV with 5 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 5);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (5 - 1);
  typedef unsigned int SORT_3;  // BV with 1 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 1);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (1 - 1);
  typedef unsigned int SORT_5;  // BV with 32 bits
  const SORT_5 mask_SORT_5 = (SORT_5)-1 >> (sizeof(SORT_5) * 8 - 32);
  const SORT_5 msb_SORT_5 = (SORT_5)1 << (32 - 1);
  typedef unsigned int SORT_24;  // BV with 31 bits
  const SORT_24 mask_SORT_24 = (SORT_24)-1 >> (sizeof(SORT_24) * 8 - 31);
  const SORT_24 msb_SORT_24 = (SORT_24)1 << (31 - 1);
  typedef unsigned int SORT_34;  // BV with 30 bits
  const SORT_34 mask_SORT_34 = (SORT_34)-1 >> (sizeof(SORT_34) * 8 - 30);
  const SORT_34 msb_SORT_34 = (SORT_34)1 << (30 - 1);
  typedef unsigned int SORT_36;  // BV with 29 bits
  const SORT_36 mask_SORT_36 = (SORT_36)-1 >> (sizeof(SORT_36) * 8 - 29);
  const SORT_36 msb_SORT_36 = (SORT_36)1 << (29 - 1);
  typedef unsigned int SORT_42;  // BV with 2 bits
  const SORT_42 mask_SORT_42 = (SORT_42)-1 >> (sizeof(SORT_42) * 8 - 2);
  const SORT_42 msb_SORT_42 = (SORT_42)1 << (2 - 1);
  typedef unsigned int SORT_48;  // BV with 28 bits
  const SORT_48 mask_SORT_48 = (SORT_48)-1 >> (sizeof(SORT_48) * 8 - 28);
  const SORT_48 msb_SORT_48 = (SORT_48)1 << (28 - 1);
  typedef unsigned int SORT_50;  // BV with 26 bits
  const SORT_50 mask_SORT_50 = (SORT_50)-1 >> (sizeof(SORT_50) * 8 - 26);
  const SORT_50 msb_SORT_50 = (SORT_50)1 << (26 - 1);
  typedef unsigned int SORT_56;  // BV with 4 bits
  const SORT_56 mask_SORT_56 = (SORT_56)-1 >> (sizeof(SORT_56) * 8 - 4);
  const SORT_56 msb_SORT_56 = (SORT_56)1 << (4 - 1);
  typedef unsigned int SORT_62;  // BV with 24 bits
  const SORT_62 mask_SORT_62 = (SORT_62)-1 >> (sizeof(SORT_62) * 8 - 24);
  const SORT_62 msb_SORT_62 = (SORT_62)1 << (24 - 1);
  typedef unsigned int SORT_64;  // BV with 20 bits
  const SORT_64 mask_SORT_64 = (SORT_64)-1 >> (sizeof(SORT_64) * 8 - 20);
  const SORT_64 msb_SORT_64 = (SORT_64)1 << (20 - 1);
  typedef unsigned int SORT_70;  // BV with 8 bits
  const SORT_70 mask_SORT_70 = (SORT_70)-1 >> (sizeof(SORT_70) * 8 - 8);
  const SORT_70 msb_SORT_70 = (SORT_70)1 << (8 - 1);
  typedef unsigned int SORT_76;  // BV with 16 bits
  const SORT_76 mask_SORT_76 = (SORT_76)-1 >> (sizeof(SORT_76) * 8 - 16);
  const SORT_76 msb_SORT_76 = (SORT_76)1 << (16 - 1);
  // Initializing constants ...
  const SORT_5 var_8 = 0;
  const SORT_5 var_12 = 2863311530;
  const SORT_3 var_14 = 1;
  const SORT_3 var_20 = 0;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_5 input_6;
  SORT_3 input_7;
  // Collecting state declarations ...
  SORT_5 state_9;
  SORT_5 state_18;
  SORT_3 state_21;
  // Initializing states ...
  SORT_5 init_10_arg_1 = var_8;
  state_9 = init_10_arg_1;
  SORT_5 init_19_arg_1 = var_8;
  state_18 = init_19_arg_1;
  SORT_3 init_22_arg_1 = var_20;
  state_21 = init_22_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_int();
    input_2 = input_2 & mask_SORT_1;
    input_4 = __VERIFIER_nondet_int();
    input_4 = input_4 & mask_SORT_3;
    input_6 = __VERIFIER_nondet_int();
    input_6 = input_6 & mask_SORT_5;
    input_7 = __VERIFIER_nondet_int();
    input_7 = input_7 & mask_SORT_3;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_5 var_13_arg_0 = state_9;
    SORT_5 var_13_arg_1 = var_12;
    SORT_3 var_13 = var_13_arg_0 != var_13_arg_1;
    SORT_3 var_15_arg_0 = var_13;
    SORT_3 var_15 = ~var_15_arg_0;
    var_15 = var_15 & mask_SORT_3;
    SORT_3 var_16_arg_0 = var_14;
    SORT_3 var_16_arg_1 = var_15;
    SORT_3 var_16 = var_16_arg_0 & var_16_arg_1;
    var_16 = var_16 & mask_SORT_3;
    SORT_3 bad_17_arg_0 = var_16;
    __VERIFIER_assert(!(bad_17_arg_0));
    // Computing next states ...
    SORT_1 var_80_arg_0 = input_2;
    SORT_3 var_80 = var_80_arg_0 >> 4;
    var_80 = var_80 & mask_SORT_3;
    SORT_1 var_67_arg_0 = input_2;
    SORT_3 var_67 = var_67_arg_0 >> 3;
    var_67 = var_67 & mask_SORT_3;
    SORT_1 var_53_arg_0 = input_2;
    SORT_3 var_53 = var_53_arg_0 >> 2;
    var_53 = var_53 & mask_SORT_3;
    SORT_1 var_39_arg_0 = input_2;
    SORT_3 var_39 = var_39_arg_0 >> 1;
    var_39 = var_39 & mask_SORT_3;
    SORT_1 var_27_arg_0 = input_2;
    SORT_3 var_27 = var_27_arg_0 >> 0;
    var_27 = var_27 & mask_SORT_3;
    SORT_5 var_30_arg_0 = state_18;
    SORT_3 var_30 = var_30_arg_0 >> 0;
    var_30 = var_30 & mask_SORT_3;
    SORT_5 var_29_arg_0 = state_18;
    SORT_3 var_29 = var_29_arg_0 >> 31;
    var_29 = var_29 & mask_SORT_3;
    SORT_3 var_31_arg_0 = var_27;
    SORT_3 var_31_arg_1 = var_30;
    SORT_3 var_31_arg_2 = var_29;
    SORT_3 var_31 = var_31_arg_0 ? var_31_arg_1 : var_31_arg_2;
    SORT_5 var_26_arg_0 = state_18;
    SORT_24 var_26 = var_26_arg_0 >> 1;
    var_26 = var_26 & mask_SORT_24;
    SORT_5 var_25_arg_0 = state_18;
    SORT_24 var_25 = var_25_arg_0 >> 0;
    var_25 = var_25 & mask_SORT_24;
    SORT_3 var_28_arg_0 = var_27;
    SORT_24 var_28_arg_1 = var_26;
    SORT_24 var_28_arg_2 = var_25;
    SORT_24 var_28 = var_28_arg_0 ? var_28_arg_1 : var_28_arg_2;
    SORT_24 var_37_arg_0 = var_28;
    SORT_36 var_37 = var_37_arg_0 >> 2;
    var_37 = var_37 & mask_SORT_36;
    SORT_3 var_38_arg_0 = var_31;
    SORT_36 var_38_arg_1 = var_37;
    SORT_34 var_38 = ((SORT_34)var_38_arg_0 << 29) | var_38_arg_1;
    SORT_24 var_35_arg_0 = var_28;
    SORT_34 var_35 = var_35_arg_0 >> 0;
    var_35 = var_35 & mask_SORT_34;
    SORT_3 var_40_arg_0 = var_39;
    SORT_34 var_40_arg_1 = var_38;
    SORT_34 var_40_arg_2 = var_35;
    SORT_34 var_40 = var_40_arg_0 ? var_40_arg_1 : var_40_arg_2;
    SORT_34 var_58_arg_0 = var_40;
    SORT_56 var_58 = var_58_arg_0 >> 0;
    var_58 = var_58 & mask_SORT_56;
    SORT_24 var_44_arg_0 = var_28;
    SORT_42 var_44 = var_44_arg_0 >> 0;
    var_44 = var_44 & mask_SORT_42;
    SORT_24 var_41_arg_0 = var_28;
    SORT_3 var_41 = var_41_arg_0 >> 30;
    var_41 = var_41 & mask_SORT_3;
    SORT_3 var_43_arg_0 = var_31;
    SORT_3 var_43_arg_1 = var_41;
    SORT_42 var_43 = ((SORT_42)var_43_arg_0 << 1) | var_43_arg_1;
    SORT_3 var_45_arg_0 = var_39;
    SORT_42 var_45_arg_1 = var_44;
    SORT_42 var_45_arg_2 = var_43;
    SORT_42 var_45 = var_45_arg_0 ? var_45_arg_1 : var_45_arg_2;
    SORT_34 var_55_arg_0 = var_40;
    SORT_42 var_55 = var_55_arg_0 >> 28;
    var_55 = var_55 & mask_SORT_42;
    SORT_42 var_57_arg_0 = var_45;
    SORT_42 var_57_arg_1 = var_55;
    SORT_56 var_57 = ((SORT_56)var_57_arg_0 << 2) | var_57_arg_1;
    SORT_3 var_59_arg_0 = var_53;
    SORT_56 var_59_arg_1 = var_58;
    SORT_56 var_59_arg_2 = var_57;
    SORT_56 var_59 = var_59_arg_0 ? var_59_arg_1 : var_59_arg_2;
    SORT_34 var_51_arg_0 = var_40;
    SORT_50 var_51 = var_51_arg_0 >> 4;
    var_51 = var_51 & mask_SORT_50;
    SORT_42 var_52_arg_0 = var_45;
    SORT_50 var_52_arg_1 = var_51;
    SORT_48 var_52 = ((SORT_48)var_52_arg_0 << 26) | var_52_arg_1;
    SORT_34 var_49_arg_0 = var_40;
    SORT_48 var_49 = var_49_arg_0 >> 0;
    var_49 = var_49 & mask_SORT_48;
    SORT_3 var_54_arg_0 = var_53;
    SORT_48 var_54_arg_1 = var_52;
    SORT_48 var_54_arg_2 = var_49;
    SORT_48 var_54 = var_54_arg_0 ? var_54_arg_1 : var_54_arg_2;
    SORT_48 var_65_arg_0 = var_54;
    SORT_64 var_65 = var_65_arg_0 >> 8;
    var_65 = var_65 & mask_SORT_64;
    SORT_56 var_66_arg_0 = var_59;
    SORT_64 var_66_arg_1 = var_65;
    SORT_62 var_66 = ((SORT_62)var_66_arg_0 << 20) | var_66_arg_1;
    SORT_48 var_63_arg_0 = var_54;
    SORT_62 var_63 = var_63_arg_0 >> 0;
    var_63 = var_63 & mask_SORT_62;
    SORT_3 var_68_arg_0 = var_67;
    SORT_62 var_68_arg_1 = var_66;
    SORT_62 var_68_arg_2 = var_63;
    SORT_62 var_68 = var_68_arg_0 ? var_68_arg_1 : var_68_arg_2;
    SORT_62 var_77_arg_0 = var_68;
    SORT_76 var_77 = var_77_arg_0 >> 0;
    var_77 = var_77 & mask_SORT_76;
    SORT_48 var_72_arg_0 = var_54;
    SORT_70 var_72 = var_72_arg_0 >> 0;
    var_72 = var_72 & mask_SORT_70;
    SORT_48 var_69_arg_0 = var_54;
    SORT_56 var_69 = var_69_arg_0 >> 24;
    var_69 = var_69 & mask_SORT_56;
    SORT_56 var_71_arg_0 = var_59;
    SORT_56 var_71_arg_1 = var_69;
    SORT_70 var_71 = ((SORT_70)var_71_arg_0 << 4) | var_71_arg_1;
    SORT_3 var_73_arg_0 = var_67;
    SORT_70 var_73_arg_1 = var_72;
    SORT_70 var_73_arg_2 = var_71;
    SORT_70 var_73 = var_73_arg_0 ? var_73_arg_1 : var_73_arg_2;
    SORT_62 var_78_arg_0 = var_68;
    SORT_70 var_78 = var_78_arg_0 >> 16;
    var_78 = var_78 & mask_SORT_70;
    SORT_70 var_79_arg_0 = var_73;
    SORT_70 var_79_arg_1 = var_78;
    SORT_76 var_79 = ((SORT_76)var_79_arg_0 << 8) | var_79_arg_1;
    SORT_3 var_82_arg_0 = var_80;
    SORT_76 var_82_arg_1 = var_77;
    SORT_76 var_82_arg_2 = var_79;
    SORT_76 var_82 = var_82_arg_0 ? var_82_arg_1 : var_82_arg_2;
    SORT_3 var_81_arg_0 = var_80;
    SORT_76 var_81_arg_1 = var_79;
    SORT_76 var_81_arg_2 = var_77;
    SORT_76 var_81 = var_81_arg_0 ? var_81_arg_1 : var_81_arg_2;
    SORT_76 var_83_arg_0 = var_82;
    SORT_76 var_83_arg_1 = var_81;
    SORT_5 var_83 = ((SORT_5)var_83_arg_0 << 16) | var_83_arg_1;
    SORT_5 next_85_arg_1 = var_83;
    SORT_3 var_86_arg_0 = state_21;
    SORT_5 var_86_arg_1 = state_9;
    SORT_5 var_86_arg_2 = input_6;
    SORT_5 var_86 = var_86_arg_0 ? var_86_arg_1 : var_86_arg_2;
    SORT_5 next_87_arg_1 = var_86;
    SORT_3 next_88_arg_1 = input_7;
    // Assigning next states ...
    state_9 = next_85_arg_1;
    state_18 = next_87_arg_1;
    state_21 = next_88_arg_1;
  }
}
