# This file is part of the SV-Benchmarks collection of verification tasks:
# https://github.com/sosy-lab/sv-benchmarks
#
# SPDX-FileCopyrightText: 2023 Levente Bajczi, Department of Measurement and Information Systems, Budapest University of Technology and Economics
#
# SPDX-License-Identifier: Apache-2.0
LEVEL := ../

include $(LEVEL)/Makefile.config
