# This file is part of the SV-Benchmarks collection of verification tasks:
# https://github.com/sosy-lab/sv-benchmarks
#
# SPDX-FileCopyrightText: 2015-2016 Daniel Liew <dan@su-root.co.uk>
# SPDX-FileCopyrightText: 2015-2020 The SV-Benchmarks Community
#
# SPDX-License-Identifier: Apache-2.0
#
LEVEL := ../

CLANG_WARNINGS := -Wno-tautological-compare -Wno-missing-braces

# These directories do not contain tasks
IGNORE_DIRS := ./original/

CC.Arch := 64
CC.Standard := c11
include $(LEVEL)/Makefile.config
