# This file is part of the SV-Benchmarks collection of verification tasks:
# https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
#
# SPDX-FileCopyrightText: 2023 Edoardo Manino
#
# SPDX-License-Identifier: MIT

LEVEL := ../

IGNORE_DIRS := ./model/
CC.Flags := -I./model
CLANG_WARNINGS := -Wno-unused-but-set-variable


include $(LEVEL)/Makefile.config

