# Copyright (C) 2023 Intel Corporation                                          
#                                                                               
# Permission is hereby granted, free of charge, to any person obtaining a copy  
# of this software and associated documentation files (the "Software"),         
# to deal in the Software without restriction, including without limitation     
# the rights to use, copy, modify, merge, publish, distribute, sublicense,      
# and/or sell copies of the Software, and to permit persons to whom             
# the Software is furnished to do so, subject to the following conditions:      
#                                                                               
# The above copyright notice and this permission notice shall be included       
# in all copies or substantial portions of the Software.                        
#                                                                               
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS       
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL      
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES             
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,      
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE            
# OR OTHER DEALINGS IN THE SOFTWARE.                                            
#                                                                               
# SPDX-License-Identifier: MIT

name: tdh_export_restore_config.yml
description: reach-safety tasks for tdh_export_restore
tasks:

  - name: tdh_export_restore__expected__safety_requirement
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__expected__precond
    after_target:
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__expected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx_with_check
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: true
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: true

  - name: tdh_export_restore__expected__cover_entry
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__expected__precond
      - filename: formal/harness/common.c
        method: insert_cover_point
    after_target:
#       - filename: formal/harness/tdh_export_restore_harness.c
#         method: tdh_export_restore__expected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false

  - name: tdh_export_restore__expected__cover_exit
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__expected__precond
    after_target:
      - filename: formal/harness/common.c
        method: insert_cover_point
#       - filename: formal/harness/tdh_export_restore_harness.c
#         method: tdh_export_restore__expected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false

  - name: tdh_export_restore__expected__cover_proof
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__expected__precond
    after_target:
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__expected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx_with_check
      - filename: formal/harness/common.c
        method: insert_cover_point
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false

  - name: tdh_export_restore__unexpected__safety_requirement
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unexpected__precond
    after_target:
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unexpected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx_with_check
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: true
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: true

  - name: tdh_export_restore__unexpected__cover_entry
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unexpected__precond
      - filename: formal/harness/common.c
        method: insert_cover_point
    after_target:
#       - filename: formal/harness/tdh_export_restore_harness.c
#         method: tdh_export_restore__unexpected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false

  - name: tdh_export_restore__unexpected__cover_exit
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unexpected__precond
    after_target:
      - filename: formal/harness/common.c
        method: insert_cover_point
#       - filename: formal/harness/tdh_export_restore_harness.c
#         method: tdh_export_restore__unexpected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false

  - name: tdh_export_restore__unexpected__cover_proof
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unexpected__precond
    after_target:
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unexpected__postcond
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx_with_check
      - filename: formal/harness/common.c
        method: insert_cover_point
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false

  #
  # Return status code coverage tasks
  #

  - name: tdh_export_restore__unconstrained__cover_exit_success
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unconstrained__precond
    after_target:
      - filename: formal/harness/common.c
        method: seam_call__exit_status_success
      - filename: formal/harness/common.c
        method: insert_cover_point
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false

  - name: tdh_export_restore__unconstrained__cover_exit_unsuccess
    target:
      filename: formal/harness/tdh_export_restore_harness.c
      method: tdh_export_restore__call
    before_target:
      - filename: formal/src/initialization.c
        method: init_tdh_export_xxx
      - filename: formal/harness/tdh_export_restore_harness.c
        method: tdh_export_restore__unconstrained__precond
    after_target:
      - filename: formal/harness/common.c
        method: seam_call__exit_status_unsuccess
      - filename: formal/harness/common.c
        method: insert_cover_point
      - filename: formal/src/initialization.c
        method: close_tdh_export_xxx
    properties:
      - property_file: ../../../properties/unreach-call.prp
        expected_verdict: false
      - property_file: ../../../properties/coverage-error-call.prp
        expected_verdict: false
